<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';
$user=require_login(['admin','office_head','supervisor']);$officeId=$user['role']==='admin'?null:(int)$user['office_id'];
$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));$selected=in_array($_GET['metric']??'',['overall','timeliness','handling','quality'],true)?(string)$_GET['metric']:'overall';
$distribution=rating_distribution($officeId,$from?:null,$to?:null);$current=$distribution[$selected];
[$where,$params]=feedback_where($officeId,$from?:null,$to?:null,true,false);$count=db()->prepare('SELECT COUNT(*) FROM feedback f JOIN offices o ON o.id=f.office_id WHERE '.implode(' AND ',$where));$count->execute($params);$p=pagination((int)$count->fetchColumn(),25);
$stmt=db()->prepare('SELECT f.*,o.code office_code FROM feedback f JOIN offices o ON o.id=f.office_id WHERE '.implode(' AND ',$where).' ORDER BY f.visit_date DESC,f.id DESC LIMIT '.$p['per_page'].' OFFSET '.$p['offset']);$stmt->execute($params);$rows=$stmt->fetchAll();
render_dashboard_start('Rating Distribution','rating_distribution');page_header('Rating Distribution & Actual Numbers','Rating breakdown and complete survey log'.($officeId?' for '.$user['office_name']:' across active offices').'.');
?>
<form class="filters wide" method="get"><label class="filter-field"><span>Start date</span><input type="date" name="from" value="<?= e($from) ?>"></label><label class="filter-field"><span>End date</span><input type="date" name="to" value="<?= e($to) ?>"></label><button class="btn">Apply Filters</button></form>
<section class="card"><div class="card-head"><div><h2>Rating Distribution</h2><p><?= $current['total'] ?> response(s) in the selected range.</p></div></div><div class="tabs"><?php foreach($distribution as $key=>$item): ?><a class="tab <?= $selected===$key?'active':'' ?>" href="?<?= e(http_build_query(['from'=>$from,'to'=>$to,'metric'=>$key])) ?>"><?= e($item['label']) ?></a><?php endforeach; ?></div><?php $labels=['4'=>['Strongly Agree','positive'],'3'=>['Agree','neutral'],'2'=>['Disagree','warning'],'1'=>['Strongly Disagree','negative']];foreach($labels as $rating=>[$label,$type]):$count=(int)$current[$rating];$percent=$current['total']?round($count/$current['total']*100):0;?><div class="bar-row"><span><?= $rating ?>. <?= e($label) ?></span><div class="bar-track"><div class="bar-fill <?= e($type) ?>" style="width:<?= $percent ?>%"></div></div><b><?= $count ?> · <?= $percent ?>%</b></div><?php endforeach; ?></section>
<section class="card" style="margin-top:16px"><div class="card-head"><div><h2>Full Actual Response Count Matrix</h2></div></div><div class="table-wrap"><table><thead><tr><th>Criteria</th><th>4 (SA)</th><th>3 (A)</th><th>2 (D)</th><th>1 (SD)</th><th>Total</th></tr></thead><tbody><?php foreach($distribution as $item): ?><tr><td><strong><?= e($item['label']) ?></strong></td><td><?= badge((string)$item['4'],'positive') ?></td><td><?= badge((string)$item['3'],'neutral') ?></td><td><?= badge((string)$item['2'],'warning') ?></td><td><?= badge((string)$item['1'],'negative') ?></td><td><strong><?= (int)$item['total'] ?></strong></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="card" style="margin-top:16px"><div class="card-head"><div><h2>Complete Survey Log Data</h2><p><?= (int)$p['total'] ?> matching record(s).</p></div></div><div class="table-wrap"><table><thead><tr><th>Assisted By</th><th>Timestamp</th><th>Client #</th><th>Client</th><th>Service</th><th>T/H/Q/O</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= e($row['assisted_by']?:'Unassigned') ?></td><td><?= e($row['visit_date']) ?></td><td><?= e($row['client_number']) ?></td><td><?= e(trim($row['surname'].' '.$row['given_name'].' '.$row['middle_initial'])) ?></td><td><?= e($row['service_received']) ?></td><td><?= (int)$row['timeliness_rating'] ?>/<?= (int)$row['client_handling_rating'] ?>/<?= (int)$row['quality_rating'] ?>/<?= (int)$row['overall_rating'] ?></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="6" class="empty-state">No survey records match the selected filters.</td></tr><?php endif; ?></tbody></table></div><?= pagination_links($p) ?></section>
<?php render_dashboard_end(); ?>
