<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['admin']);
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$id=post_int('action_id');$status=(string)($_POST['status']??'');$notes=trim((string)($_POST['resolution_notes']??''));
 try{if(!in_array($status,['needs_action','in_progress','pending_approval','completed'],true)||mb_strlen($notes)<5)throw new RuntimeException('Select a valid status and enter notes.');$stmt=db()->prepare('SELECT * FROM actions WHERE id=?');$stmt->execute([$id]);$a=$stmt->fetch();if(!$a)throw new RuntimeException('Action not found.');$completed=$status==='completed'?date('Y-m-d H:i:s'):null;$approved=$status==='completed'?(int)$user['id']:null;db()->prepare('UPDATE actions SET status=?,resolution_notes=?,completed_at=?,approved_by_user_id=?,approved_at=IF(? IS NULL,NULL,NOW()) WHERE id=?')->execute([$status,$notes,$completed,$approved,$approved,$id]);audit((int)$user['id'],'admin_action_update',"Action #{$id} -> {$status}");if($status==='completed')notify_office_heads((int)$a['office_id'],'action','Action completed by administrator','Action #'.$id.' was marked completed by the administrator.','office/actions.php');set_flash('success','Action item updated.');}catch(Throwable $e){set_flash('error',$e->getMessage());}redirect('admin/actions.php');
}
$officeId=request_int('office_id');$status=trim((string)($_GET['status']??''));$q=trim((string)($_GET['q']??''));$where=["o.status='active'"];$params=[];if($officeId){$where[]='a.office_id=?';$params[]=$officeId;}if(in_array($status,['needs_action','in_progress','pending_approval','completed'],true)){$where[]='a.status=?';$params[]=$status;}if($q!==''){$where[]='(a.title LIKE ? OR a.details LIKE ? OR a.resolution_notes LIKE ? OR CAST(a.id AS CHAR)=?)';$params[]="%{$q}%";$params[]="%{$q}%";$params[]="%{$q}%";$params[]=$q;}
$count=db()->prepare('SELECT COUNT(*) FROM actions a JOIN offices o ON o.id=a.office_id WHERE '.implode(' AND ',$where));$count->execute($params);$p=pagination((int)$count->fetchColumn(),20);$stmt=db()->prepare("SELECT a.*,o.name office_name,o.code office_code,f.sentiment,f.final_score FROM actions a JOIN offices o ON o.id=a.office_id LEFT JOIN feedback f ON f.id=a.feedback_id WHERE ".implode(' AND ',$where)." ORDER BY FIELD(a.status,'pending_approval','needs_action','in_progress','completed'),a.updated_at DESC LIMIT {$p['per_page']} OFFSET {$p['offset']}");$stmt->execute($params);$rows=$stmt->fetchAll();$offices=active_offices();
render_dashboard_start('Action Management','actions');page_header('Action Management','Monitor and audit concerns across all active offices. Office Heads remain responsible for ordinary completion approval.');
?>
<form class="filters wide" method="get"><select name="office_id"><option value="0">All active offices</option><?php foreach($offices as $o):?><option value="<?= (int)$o['id'] ?>" <?= $officeId===(int)$o['id']?'selected':'' ?>><?= e($o['code']) ?> — <?= e($o['name']) ?></option><?php endforeach;?></select><select name="status"><option value="">All status</option><?php foreach(['needs_action','in_progress','pending_approval','completed'] as $v):?><option value="<?= $v ?>" <?= $status===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><input name="q" value="<?= e($q) ?>" placeholder="Search action ID, title, notes"><button class="btn">Apply</button></form>
<section class="card"><div class="table-wrap"><table><thead><tr><th>Action</th><th>Office</th><th>Source</th><th>Status / Resolution</th><th>Updated</th></tr></thead><tbody><?php foreach($rows as $a):?><tr><td><strong>#<?= (int)$a['id'] ?> · <?= e($a['title']) ?></strong><br><span class="muted"><?= e($a['details']) ?></span></td><td><?= e($a['office_code']) ?><br><span class="muted"><?= e($a['office_name']) ?></span></td><td><?= $a['feedback_id']?'#'.(int)$a['feedback_id']:'Manual' ?><?php if($a['sentiment']): ?><br><?= badge(status_label($a['sentiment']),$a['sentiment']) ?> · <?= number_format((float)$a['final_score'],2) ?>%<?php endif; ?></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action_id" value="<?= (int)$a['id'] ?>"><select name="status"><?php foreach(['needs_action','in_progress','pending_approval','completed'] as $v):?><option value="<?= $v ?>" <?= $a['status']===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><textarea name="resolution_notes" required><?= e($a['resolution_notes']) ?></textarea><button class="btn small">Save Override</button></form></td><td><?= e(date('M d, Y h:i A',strtotime($a['updated_at']))) ?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="5" class="empty-state">No action items.</td></tr><?php endif;?></tbody></table></div><?= pagination_links($p) ?></section>
<?php render_dashboard_end(); ?>
