<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$admin=require_login(['admin']);
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$id=post_int('action_id');$status=(string)($_POST['status']??'');$notes=trim((string)($_POST['resolution_notes']??''));
 if(in_array($status,['needs_action','in_progress','completed'],true)){if($notes===''){set_flash('error','Enter review or resolution notes before saving the action.');redirect('admin/actions.php');}
  $completed=$status==='completed'?date('Y-m-d H:i:s'):null;$stmt=db()->prepare('UPDATE actions SET status=?,resolution_notes=?,completed_at=? WHERE id=?');$stmt->execute([$status,$notes,$completed,$id]);audit((int)$admin['id'],'action_update',"Action #{$id} -> {$status}");set_flash('success','Action status updated.');
 }
 redirect('admin/actions.php');
}
$officeId=request_int('office_id');$status=trim((string)($_GET['status']??''));$where=['1=1'];$params=[];if($officeId){$where[]='a.office_id=?';$params[]=$officeId;}if(in_array($status,['needs_action','in_progress','completed'],true)){$where[]='a.status=?';$params[]=$status;}
$stmt=db()->prepare("SELECT a.*,o.name office_name,o.code office_code,f.comment,f.final_score,f.sentiment FROM actions a JOIN offices o ON o.id=a.office_id LEFT JOIN feedback f ON f.id=a.feedback_id WHERE ".implode(' AND ',$where)." ORDER BY FIELD(a.status,'needs_action','in_progress','completed'),a.updated_at DESC");$stmt->execute($params);$rows=$stmt->fetchAll();$offices=db()->query('SELECT * FROM offices ORDER BY name')->fetchAll();
render_dashboard_start('Action Management','actions');page_header('Action Management','Monitor concerns generated from negative comments or final scores below the threshold.');
?>
<div class="tabs"><a class="tab <?= $status===''?'active':'' ?>" href="?<?= $officeId?'office_id='.$officeId:'' ?>">All</a><?php foreach(['needs_action','in_progress','completed'] as $v):?><a class="tab <?= $status===$v?'active':'' ?>" href="?status=<?= e($v) ?><?= $officeId?'&office_id='.$officeId:'' ?>"><?= e(status_label($v)) ?></a><?php endforeach;?></div>
<form class="filters" method="get"><select name="office_id"><option value="0">All offices</option><?php foreach($offices as $o):?><option value="<?= (int)$o['id'] ?>" <?= $officeId===(int)$o['id']?'selected':'' ?>><?= e($o['code']) ?> — <?= e($o['name']) ?></option><?php endforeach;?></select><select name="status"><option value="">All status</option><?php foreach(['needs_action','in_progress','completed'] as $v):?><option value="<?= $v ?>" <?= $status===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><button class="btn">Apply</button></form>
<section class="card"><div class="table-wrap"><table><thead><tr><th>Action</th><th>Office</th><th>Source Feedback</th><th>Status / Resolution</th><th>Updated</th></tr></thead><tbody><?php foreach($rows as $a):?><tr><td><strong><?= e($a['title']) ?></strong><br><span class="muted"><?= e($a['details']) ?></span></td><td><?= e($a['office_code']) ?><br><span class="muted"><?= e($a['office_name']) ?></span></td><td><?= $a['feedback_id']?'#'.(int)$a['feedback_id']:'Manual' ?> · <?= $a['sentiment']?badge(status_label($a['sentiment']),$a['sentiment']):'' ?><br><span class="muted"><?= $a['final_score']!==null?number_format((float)$a['final_score'],2).'%':'' ?></span></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action_id" value="<?= (int)$a['id'] ?>"><select name="status"><?php foreach(['needs_action','in_progress','completed'] as $v):?><option value="<?= $v ?>" <?= $a['status']===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><textarea name="resolution_notes" placeholder="Review or resolution notes" required><?= e($a['resolution_notes']) ?></textarea><button class="btn small">Save</button></form></td><td><?= e(date('M d, Y h:i A',strtotime($a['updated_at']))) ?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="5" class="empty-state">No action items.</td></tr><?php endif;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
