<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/simple_pdf.php';
$user=require_login(['admin']);$exportPdf=($_GET['export']??'')==='pdf';$exportScope=in_array(($_GET['scope']??''),['summary','complete'],true)?(string)$_GET['scope']:'complete';$m=dashboard_metrics();$trend=monthly_trend();$indicators=indicator_averages();$comparison=office_comparison();$recent=recent_feedback();$ages=age_group_counts();$services=service_summary(null,8);$terms=frequent_concern_terms();$allResponses=[];if($exportPdf){if($exportScope==='complete')$allResponses=db()->query("SELECT f.visit_date,o.code AS office_code,f.sex,f.age,f.client_type,f.service_received,f.timeliness_rating,f.client_handling_rating,f.quality_rating,f.overall_rating,f.average_rating,f.sentiment,f.review_status,f.final_score,f.comment FROM feedback f JOIN offices o ON o.id=f.office_id WHERE f.is_void=0 AND o.status='active' ORDER BY f.visit_date DESC,f.id DESC")->fetchAll();audit((int)$user['id'],'dashboard_pdf_export','Downloaded consolidated '.$exportScope.' dashboard PDF');download_feedback_report_pdf($m,$ages,$services,$allResponses,'All active offices','Dashboard '.$exportScope.' snapshot as of '.date('M d, Y h:i A'));}$headerActions='<a class="btn" href="'.e(app_url('admin/offices.php')).'">Add Office</a>'.($exportPdf?'':'<button type="button" class="btn secondary" data-modal-open="dashboard-export-modal">Download Dashboard PDF</button>');render_dashboard_start('Administrator Overview','overview');page_header('Administrator Overview','Consolidated, active-office service-satisfaction monitoring with data-quality and action indicators.',$headerActions);
$output=client_output_summary();$sex=demographic_counts(null,'sex');$clientTypes=demographic_counts(null,'client_type');
?>
<section class="overview-output-grid" aria-label="Pangkalahatang client output at ratings">
  <div class="overview-kpi output"><small>Total Output</small><strong><?= (int)$output['total'] ?></strong><span>kabuuang naproseso</span></div>
  <div class="overview-kpi average"><small>Avg. Daily Output</small><strong><?= number_format((float)$output['average'],1) ?></strong><span>client bawat active day</span></div>
  <div class="overview-kpi peak"><small>Peak Daily Output</small><strong><?= (int)$output['peak'] ?></strong><span><?= $output['peak_date']?e(date('M d, Y',strtotime($output['peak_date']))):'Wala pang datos' ?></span></div>
  <div class="overview-kpi satisfaction"><small>Satisfaction</small><strong><?= number_format((float)$m['positive_rate'],1) ?>%</strong><span>positive feedback</span></div>
  <div class="overview-kpi overall"><small>Overall Score</small><strong><?= number_format((float)($indicators['Overall Satisfaction']??0),2) ?></strong><span>mula sa 4.00</span></div>
  <div class="overview-kpi timeliness"><small>Timeliness</small><strong><?= number_format((float)($indicators['Timeliness']??0),2) ?></strong><span>bilis ng serbisyo</span></div>
  <div class="overview-kpi handling"><small>Handling</small><strong><?= number_format((float)($indicators['Client Handling']??0),2) ?></strong><span>pakikitungo</span></div>
  <div class="overview-kpi quality"><small>Quality</small><strong><?= number_format((float)($indicators['Quality of Service']??0),2) ?></strong><span>kalidad ng serbisyo</span></div>
</section>
<?php if(!$exportPdf): ?><div class="app-modal" id="dashboard-export-modal" aria-hidden="true"><section class="app-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="dashboard-export-title"><button type="button" class="modal-close" data-modal-close>&times;</button><h2 id="dashboard-export-title">Export Dashboard PDF</h2><p class="muted">Choose how much information to include.</p><form method="get" target="_blank" class="modal-form"><input type="hidden" name="export" value="pdf"><div class="scope-options"><label class="scope-option"><input type="radio" name="scope" value="summary" checked><span><strong>Dashboard summary</strong><br><small>Metrics, charts, comparisons, and recent feedback.</small></span></label><label class="scope-option"><input type="radio" name="scope" value="complete"><span><strong>Complete report</strong><br><small>Summary plus every non-void response from active offices.</small></span></label></div><div class="confirm-actions"><button type="button" class="btn secondary" data-modal-close>Cancel</button><button class="btn">Open PDF Preview</button></div></form></section></div><?php endif; ?>
<?php if($exportPdf):?><section class="report-cover"><img src="<?= e(app_url('assets/images/241304413_194220316131017_8817860418863376271_n.jpg')) ?>" alt=""><div><h1>City Government of Pasig</h1><p>Consolidated Service Feedback Dashboard Report</p><small>All active offices · Generated <?= e(date('F d, Y h:i A')) ?></small></div></section><?php endif;?>
<div class="stats-grid"><div class="stat-card highlight"><small>Total Responses</small><strong><?= $m['total'] ?></strong><span>Non-void records from active offices</span></div><div class="stat-card"><small>Final Satisfaction</small><strong><?= number_format($m['avg_final'],1) ?>%</strong><span><?= e(final_interpretation($m['avg_final'])) ?></span></div><div class="stat-card"><small>Positive Sentiment</small><strong><?= number_format($m['positive_rate'],1) ?>%</strong><span><?= $m['positive'] ?> positive comments</span></div><div class="stat-card"><small>Needs Review</small><strong><?= $m['review_count'] ?></strong><span><?= $m['fallback_count'] ?> fallback classification(s)</span></div><div class="stat-card"><small>Pending Approval</small><strong><?= $m['pending_approval'] ?></strong><span><?= number_format($m['completion_rate'],1) ?>% action completion</span></div></div>
<div class="content-grid"><section class="card"><div class="card-head"><div><h2>Six-Month Satisfaction Trend</h2><p>Average final weighted score</p></div></div><div class="chart-box"><canvas data-chart='<?= e(json_encode($trend)) ?>' data-type="line"></canvas></div></section><section class="card"><div class="card-head"><div><h2>Sentiment Distribution</h2><p>SVM/manual verified output</p></div></div><div class="sentiment-stack"><div class="sentiment-box positive"><strong><?= $m['positive'] ?></strong><span>Positive</span></div><div class="sentiment-box neutral"><strong><?= $m['neutral'] ?></strong><span>Neutral</span></div><div class="sentiment-box negative"><strong><?= $m['negative'] ?></strong><span>Negative</span></div></div><h2 style="margin-top:24px">Indicator Averages</h2><div class="bar-list"><?php foreach($indicators as $label=>$value):?><div class="bar-row"><span><?= e($label) ?></span><div class="bar-track"><div class="bar-fill" style="width:<?= min(100,($value/4)*100) ?>%"></div></div><b><?= number_format($value,2) ?></b></div><?php endforeach;?></div></section></div>
<section class="card demographics-card"><div class="card-head"><div><h2>Demographics</h2><p>Pinagsama-samang profile ng mga respondent mula sa active offices.</p></div></div><div class="demographic-grid"><div><h3>Sex</h3><?php foreach($sex as $r):?><p><span><?= e($r['label']) ?></span><strong><?= (int)$r['count'] ?></strong></p><?php endforeach;?><?php if(!$sex):?><p class="muted">Wala pang datos.</p><?php endif;?></div><div><h3>Client Type</h3><?php foreach($clientTypes as $r):?><p><span><?= e($r['label']) ?></span><strong><?= (int)$r['count'] ?></strong></p><?php endforeach;?><?php if(!$clientTypes):?><p class="muted">Wala pang datos.</p><?php endif;?></div><div><h3>Age Groups</h3><?php foreach($ages as $r):?><p><span><?= e($r['label']) ?></span><strong><?= (int)$r['count'] ?></strong></p><?php endforeach;?><?php if(!$ages):?><p class="muted">Wala pang datos.</p><?php endif;?></div></div></section>
<section class="card"><div class="card-head"><div><h2>Action Timeliness</h2></div></div><div class="stats-grid mini"><div class="stat-card"><small>Average Open Age</small><strong><?= number_format($m['avg_open_hours']/24,1) ?></strong><span>days</span></div><div class="stat-card"><small>Average Resolution</small><strong><?= number_format($m['avg_resolution_hours']/24,1) ?></strong><span>days</span></div></div><h2>Frequent Services</h2><div class="bar-list"><?php foreach($services as $s):?><div><strong><?= e($s['label']) ?></strong><br><span class="muted"><?= (int)$s['responses'] ?> responses · <?= number_format((float)$s['avg_score'],1) ?>% score</span></div><?php endforeach;?></div></section>
<?php if($exportPdf):?><section class="card complete-responses"><div class="card-head"><div><h2>Complete Feedback Responses — All Active Offices</h2><p><?= count($allResponses) ?> non-void response(s) included in this consolidated report.</p></div></div><div class="table-wrap"><table><thead><tr><th>Date / Office</th><th>Respondent</th><th>Service</th><th>Ratings (T/H/Q/O)</th><th>Sentiment / Review</th><th>Score</th><th>Comment</th></tr></thead><tbody><?php foreach($allResponses as $r):?><tr><td><?= e($r['visit_date']) ?><br><strong><?= e($r['office_code']) ?></strong></td><td><?= e($r['sex']) ?>, <?= (int)$r['age'] ?><br><?= e($r['client_type']) ?></td><td><?= e($r['service_received']) ?></td><td><?= (int)$r['timeliness_rating'] ?>/<?= (int)$r['client_handling_rating'] ?>/<?= (int)$r['quality_rating'] ?>/<?= (int)$r['overall_rating'] ?></td><td><?= e(status_label($r['sentiment'])) ?><br><?= e(status_label($r['review_status'])) ?></td><td><?= number_format((float)$r['final_score'],2) ?>%</td><td><?= e($r['comment']) ?></td></tr><?php endforeach;?><?php if(!$allResponses):?><tr><td colspan="7" class="empty-state">No feedback responses available.</td></tr><?php endif;?></tbody></table></div></section><script>history.replaceState({},document.title,location.pathname);window.addEventListener('load',()=>setTimeout(()=>window.print(),500));</script><?php endif;?>
<?php if($exportPdf&&$exportScope==='summary'):?><script>document.querySelector('.complete-responses')?.remove();</script><?php endif;?><?php render_dashboard_end(); ?>
