<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user = require_login(['admin']);
$officeId=request_int('office_id');$sentiment=trim((string)($_GET['sentiment']??''));$source=trim((string)($_GET['source']??''));$review=trim((string)($_GET['review']??''));$dateFrom=trim((string)($_GET['date_from']??''));$dateTo=trim((string)($_GET['date_to']??''));$q=trim((string)($_GET['q']??''));$includeVoid=isset($_GET['include_void']);
$where=['1=1'];$params=[];
if($officeId){$where[]='f.office_id=?';$params[]=$officeId;}
if(in_array($sentiment,['positive','neutral','negative'],true)){$where[]='f.sentiment=?';$params[]=$sentiment;}
if(in_array($source,['public_survey','csv_import','manual_entry','assisted_survey'],true)){$where[]='f.source=?';$params[]=$source;}
if(in_array($review,['not_required','needs_review','reviewed'],true)){$where[]='f.review_status=?';$params[]=$review;}
if($dateFrom!==''){$where[]='f.visit_date>=?';$params[]=$dateFrom;}
if($dateTo!==''){$where[]='f.visit_date<=?';$params[]=$dateTo;}
if(!$includeVoid)$where[]='f.is_void=0';
if($q!==''){$where[]='(f.comment LIKE ? OR f.service_received LIKE ? OR CAST(f.id AS CHAR)=?)';$params[]="%{$q}%";$params[]="%{$q}%";$params[]=$q;}
$count=db()->prepare('SELECT COUNT(*) FROM feedback f WHERE '.implode(' AND ',$where));$count->execute($params);$p=pagination((int)$count->fetchColumn(),25);
$stmt=db()->prepare("SELECT f.*,o.name office_name,o.code office_code FROM feedback f JOIN offices o ON o.id=f.office_id WHERE ".implode(' AND ',$where)." ORDER BY f.submitted_at DESC LIMIT {$p['per_page']} OFFSET {$p['offset']}");$stmt->execute($params);$rows=$stmt->fetchAll();$offices=db()->query('SELECT * FROM offices ORDER BY status=\'active\' DESC,name')->fetchAll();
render_dashboard_start('Feedback Records','feedback');page_header('Feedback Records','Search and review ratings, SVM output, weighted scores, classifier source, and review state.','<a class="btn" href="'.e(app_url('review.php')).'">Open Sentiment Review</a>');
?>
<div class="sentiment-review-page">
<form class="filters wide" method="get"><select name="office_id"><option value="0">All offices</option><?php foreach($offices as $o):?><option value="<?= (int)$o['id'] ?>" <?= $officeId===(int)$o['id']?'selected':'' ?>><?= e($o['code']) ?> — <?= e($o['name']) ?><?= $o['status']==='archived'?' (Archived)':'' ?></option><?php endforeach;?></select><select name="sentiment"><option value="">All sentiments</option><?php foreach(['positive','neutral','negative'] as $v):?><option value="<?= $v ?>" <?= $sentiment===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><select name="review"><option value="">All review states</option><?php foreach(['needs_review','reviewed','not_required'] as $v):?><option value="<?= $v ?>" <?= $review===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><select name="source"><option value="">All sources</option><?php foreach(['public_survey','csv_import','manual_entry'] as $v):?><option value="<?= $v ?>" <?= $source===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><label class="filter-field"><span>From</span><input type="date" name="date_from" value="<?= e($dateFrom) ?>"></label><label class="filter-field"><span>To</span><input type="date" name="date_to" value="<?= e($dateTo) ?>"></label><input name="q" value="<?= e($q) ?>" placeholder="Search ID, service, comment"><label class="checkbox-inline"><input type="checkbox" name="include_void" value="1" <?= $includeVoid?'checked':'' ?>> Include void</label><button class="btn">Apply</button></form>
<section class="card"><div class="card-head"><div><h2>Filtered Records</h2><p><?= (int)$p['total'] ?> matching record(s)</p></div></div><div class="table-wrap"><table><thead><tr><th>Assisted By</th><th>Timestamp</th><th>Client Number</th><th>Surname</th><th>Given Name</th><th>Middle Name</th><th>Sex</th><th>Age</th><th>Types of Client</th><th>Transaction / Service</th><th>Bilis ng Serbisyo (Timeliness)</th><th>Pakikitungo sa Kliyente (Client Handling)</th><th>Kalidad ng Serbisyo (Quality of Service)</th><th>Overall Satisfaction</th><th>Prediction</th><th>Weighted Result</th></tr></thead><tbody><?php foreach($rows as $r):?><tr class="<?= $r['is_void']?'void-row':'' ?>"><td><?= e($r['assisted_by'] ?: 'Unassigned') ?><br><small class="muted">#<?= (int)$r['id'] ?> · <?= e($r['office_code']) ?></small></td><td><?= e($r['visit_date']) ?><br><small class="muted"><?= e(status_label($r['source'])) ?></small></td><td><?= e($r['client_number'] ?: '—') ?></td><td><?= e($r['surname'] ?: '—') ?></td><td><?= e($r['given_name'] ?: '—') ?></td><td><?= e($r['middle_initial'] ?: '—') ?></td><td><?= e($r['sex']) ?></td><td><?= (int)$r['age'] ?></td><td><?= e($r['client_type']) ?></td><td><?= e($r['service_received']) ?><p class="help"><?= e($r['comment']) ?></p><?php if($r['is_void']): ?><?= badge('Void','negative') ?><?php if($r['void_reason']): ?><p class="help">Void reason: <?= e($r['void_reason']) ?></p><?php endif; ?><?php endif; ?></td><td><?= (int)$r['timeliness_rating'] ?></td><td><?= (int)$r['client_handling_rating'] ?></td><td><?= (int)$r['quality_rating'] ?></td><td><?= (int)$r['overall_rating'] ?></td><td><?= badge(status_label($r['sentiment']),$r['sentiment']) ?><br><span class="muted"><?= number_format((float)$r['sentiment_confidence']*100,2) ?>% · <?= e($r['sentiment_source']) ?></span><br><?= badge(status_label($r['review_status']),$r['review_status']==='needs_review'?'negative':'positive') ?></td><td><strong><?= number_format((float)$r['final_score'],2) ?>%</strong><br><span class="muted"><?= e(final_interpretation((float)$r['final_score'])) ?></span></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="16" class="empty-state">No records match the selected filters.</td></tr><?php endif;?></tbody></table></div><?= pagination_links($p) ?></section>
</div>
<?php render_dashboard_end(); ?>
