<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_login(['admin']);
$officeId=request_int('office_id');$sentiment=trim((string)($_GET['sentiment']??''));$source=trim((string)($_GET['source']??''));$dateFrom=trim((string)($_GET['date_from']??''));$dateTo=trim((string)($_GET['date_to']??''));
$where=['1=1'];$params=[];
if($officeId){$where[]='f.office_id=?';$params[]=$officeId;}
if(in_array($sentiment,['positive','neutral','negative'],true)){$where[]='f.sentiment=?';$params[]=$sentiment;}
if(in_array($source,['public_survey','csv_import','manual_entry'],true)){$where[]='f.source=?';$params[]=$source;}
if($dateFrom!==''){$where[]='f.visit_date>=?';$params[]=$dateFrom;}
if($dateTo!==''){$where[]='f.visit_date<=?';$params[]=$dateTo;}
$sql="SELECT f.*,o.name office_name,o.code office_code FROM feedback f JOIN offices o ON o.id=f.office_id WHERE ".implode(' AND ',$where)." ORDER BY f.submitted_at DESC LIMIT 500";$stmt=db()->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();$offices=db()->query('SELECT * FROM offices ORDER BY name')->fetchAll();
render_dashboard_start('Feedback Records','feedback');page_header('Feedback Records','Review submitted ratings, comments, SVM results, weighted scores, and source.','<a class="btn secondary" href="'.e(app_url('admin/reports.php')).'">Export CSV</a>');
?>
<form class="filters" method="get"><select name="office_id"><option value="0">All offices</option><?php foreach($offices as $o):?><option value="<?= (int)$o['id'] ?>" <?= $officeId===(int)$o['id']?'selected':'' ?>><?= e($o['code']) ?> — <?= e($o['name']) ?></option><?php endforeach;?></select><select name="sentiment"><option value="">All sentiments</option><?php foreach(['positive','neutral','negative'] as $v):?><option value="<?= $v ?>" <?= $sentiment===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><select name="source"><option value="">All sources</option><?php foreach(['public_survey','csv_import','manual_entry'] as $v):?><option value="<?= $v ?>" <?= $source===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><input type="date" name="date_from" value="<?= e($dateFrom) ?>"><input type="date" name="date_to" value="<?= e($dateTo) ?>"><button class="btn">Filter</button></form>
<section class="card"><div class="card-head"><div><h2>Results</h2><p><?= count($rows) ?> record(s), limited to 500 per view</p></div></div><div class="table-wrap"><table><thead><tr><th>Date/Office</th><th>Client</th><th>Service</th><th>Ratings</th><th>Sentiment</th><th>Final</th><th>Comment</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?= e(date('M d, Y',strtotime($r['visit_date']))) ?></strong><br><span class="muted"><?= e($r['office_code']) ?> · <?= e(status_label($r['source'])) ?></span></td><td><?= e($r['sex']) ?>, <?= (int)$r['age'] ?><br><span class="muted"><?= e($r['client_type']) ?></span></td><td><?= e($r['service_received']) ?></td><td>T <?= (int)$r['timeliness_rating'] ?> · H <?= (int)$r['client_handling_rating'] ?> · Q <?= (int)$r['quality_rating'] ?> · O <?= (int)$r['overall_rating'] ?><br><span class="muted">Avg <?= number_format((float)$r['average_rating'],2) ?>/4</span></td><td><?= badge(status_label($r['sentiment']),$r['sentiment']) ?><br><span class="muted"><?= e(strtoupper($r['sentiment_source'])) ?> · <?= number_format((float)$r['sentiment_confidence']*100,1) ?>%</span></td><td><strong><?= number_format((float)$r['final_score'],2) ?>%</strong><br><span class="muted"><?= e(final_interpretation((float)$r['final_score'])) ?></span></td><td><?= e($r['comment']) ?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="7" class="empty-state">No records match the filters.</td></tr><?php endif;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
