<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$admin=require_login(['admin']);
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $action=(string)($_POST['action']??'');
 try{
  if($action==='create'){
   $officeId=post_int('office_id');$name=trim((string)$_POST['full_name']);$username=trim((string)$_POST['username']);$email=trim((string)$_POST['email']);$password=(string)$_POST['password'];
   if(!$officeId||$name===''||$username===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<8)throw new RuntimeException('Complete all fields. Password must be at least 8 characters.');
   $check=db()->prepare("SELECT COUNT(*) FROM users WHERE office_id=? AND role='office_head' AND status='active'");$check->execute([$officeId]);if((int)$check->fetchColumn()>0)throw new RuntimeException('This office already has an active Office Head. Archive the current head before creating a replacement.');
   $stmt=db()->prepare("INSERT INTO users(office_id,full_name,username,email,password_hash,role,status,created_by_user_id) VALUES(?,?,?,?,?,'office_head','active',?)");$stmt->execute([$officeId,$name,$username,$email,password_hash($password,PASSWORD_DEFAULT),(int)$admin['id']]);
   audit((int)$admin['id'],'head_create',"Created head {$username} for office #{$officeId}");set_flash('success','Office Head account created. The office dashboard is available immediately.');
  }elseif($action==='edit'){
   $id=post_int('user_id');$officeId=post_int('office_id');$name=trim((string)$_POST['full_name']);$username=trim((string)$_POST['username']);$email=trim((string)$_POST['email']);$password=(string)($_POST['password']??'');
   $currentStmt=db()->prepare("SELECT status FROM users WHERE id=? AND role='office_head'");$currentStmt->execute([$id]);$current=$currentStmt->fetch();if(!$current)throw new RuntimeException('Office Head account not found.');if($current['status']==='active'){$check=db()->prepare("SELECT COUNT(*) FROM users WHERE office_id=? AND role='office_head' AND status='active' AND id<>?");$check->execute([$officeId,$id]);if((int)$check->fetchColumn()>0)throw new RuntimeException('The selected office already has another active Office Head.');}
   if($password!==''){$stmt=db()->prepare("UPDATE users SET office_id=?,full_name=?,username=?,email=?,password_hash=? WHERE id=? AND role='office_head'");$stmt->execute([$officeId,$name,$username,$email,password_hash($password,PASSWORD_DEFAULT),$id]);}
   else{$stmt=db()->prepare("UPDATE users SET office_id=?,full_name=?,username=?,email=? WHERE id=? AND role='office_head'");$stmt->execute([$officeId,$name,$username,$email,$id]);}
   set_flash('success','Office Head account updated.');
  }elseif($action==='status'){
   $id=post_int('user_id');$status=(string)$_POST['status'];if(!in_array($status,['active','archived'],true))throw new RuntimeException('Invalid account status.');if($status==='active'){$officeStmt=db()->prepare("SELECT office_id FROM users WHERE id=? AND role='office_head'");$officeStmt->execute([$id]);$targetOffice=(int)$officeStmt->fetchColumn();$check=db()->prepare("SELECT COUNT(*) FROM users WHERE office_id=? AND role='office_head' AND status='active' AND id<>?");$check->execute([$targetOffice,$id]);if((int)$check->fetchColumn()>0)throw new RuntimeException('This office already has another active Office Head.');}
   $stmt=db()->prepare("UPDATE users SET status=? WHERE id=? AND role='office_head'");$stmt->execute([$status,$id]);set_flash('success','Office Head status updated.');
  }elseif($action==='delete'){
   $id=post_int('user_id');$stmt=db()->prepare("DELETE FROM users WHERE id=? AND role='office_head'");$stmt->execute([$id]);set_flash('success','Office Head account permanently deleted.');
  }
 }catch(Throwable $e){set_flash('error','Unable to complete action: '.$e->getMessage());}
 redirect('admin/heads.php');
}
$offices=active_offices();
$heads=db()->query("SELECT u.*,o.name office_name,o.code office_code FROM users u LEFT JOIN offices o ON o.id=u.office_id WHERE u.role='office_head' ORDER BY o.name,u.full_name")->fetchAll();
render_dashboard_start('Manage Office Heads','heads');page_header('Manage Office Heads','Create, edit, archive, reactivate, or delete Office Head accounts.');
?>
<div class="split-grid">
<section class="panel-form"><h2>Add Office Head</h2><p>Assign the account to one office. It will automatically use that office's dashboard and records.</p><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="create"><div class="form-group"><label>Assigned Office</label><select name="office_id" required><option value="">Select office</option><?php foreach($offices as $o):?><option value="<?= (int)$o['id'] ?>"><?= e($o['name']) ?> (<?= e($o['code']) ?>)</option><?php endforeach;?></select></div><div class="form-group"><label>Full Name</label><input name="full_name" required></div><div class="form-row"><div class="form-group"><label>Username</label><input name="username" required></div><div class="form-group"><label>Email</label><input type="email" name="email" required></div></div><div class="form-group"><label>Temporary Password</label><input type="password" name="password" minlength="8" required></div><button class="btn">Create Head Account</button></form></section>
<section class="card"><div class="card-head"><div><h2>Office Head Directory</h2><p><?= count($heads) ?> registered account(s)</p></div></div><div class="table-wrap"><table><thead><tr><th>Office Head</th><th>Office</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody><?php foreach($heads as $h):?><tr><td><strong><?= e($h['full_name']) ?></strong><br><span class="muted"><?= e($h['username']) ?> · <?= e($h['email']) ?></span></td><td><?= e($h['office_name']??'Unassigned') ?><br><span class="muted"><?= e($h['office_code']??'') ?></span></td><td><?= badge(status_label($h['status']),$h['status']) ?></td><td><?= e(date('M d, Y',strtotime($h['created_at']))) ?></td><td class="actions-cell"><details><summary class="btn secondary small">Edit</summary><form method="post" style="min-width:300px;padding-top:10px"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="edit"><input type="hidden" name="user_id" value="<?= (int)$h['id'] ?>"><div class="form-group"><select name="office_id" required><?php foreach($offices as $o):?><option value="<?= (int)$o['id'] ?>" <?= (int)$o['id']===(int)$h['office_id']?'selected':'' ?>><?= e($o['name']) ?></option><?php endforeach;?></select></div><div class="form-group"><input name="full_name" value="<?= e($h['full_name']) ?>" required></div><div class="form-group"><input name="username" value="<?= e($h['username']) ?>" required></div><div class="form-group"><input type="email" name="email" value="<?= e($h['email']) ?>" required></div><div class="form-group"><input type="password" name="password" placeholder="New password (optional)"></div><button class="btn small">Save Changes</button></form></details><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="status"><input type="hidden" name="user_id" value="<?= (int)$h['id'] ?>"><input type="hidden" name="status" value="<?= $h['status']==='active'?'archived':'active' ?>"><button class="btn <?= $h['status']==='active'?'danger':'success' ?> small"><?= $h['status']==='active'?'Archive':'Reactivate' ?></button></form><form method="post" data-confirm-delete="Permanently delete this Office Head account?"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="user_id" value="<?= (int)$h['id'] ?>"><button class="btn danger small">Delete</button></form></td></tr><?php endforeach;?><?php if(!$heads):?><tr><td colspan="5" class="empty-state">No Office Head accounts.</td></tr><?php endif;?></tbody></table></div></section>
</div>
<?php render_dashboard_end(); ?>
