<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['admin']);$exportPdf=($_GET['export']??'')==='pdf';$officeId=request_int('office_id');$dateFrom=trim((string)($_GET['date_from']??''));$dateTo=trim((string)($_GET['date_to']??''));$includeArchived=isset($_GET['include_archived']);$includeVoid=isset($_GET['include_void']);
$where=['1=1'];$params=[];if($officeId){$where[]='f.office_id=?';$params[]=$officeId;}if($dateFrom!==''){$where[]='f.visit_date>=?';$params[]=$dateFrom;}if($dateTo!==''){$where[]='f.visit_date<=?';$params[]=$dateTo;}if(!$includeArchived)$where[]="o.status='active'";if(!$includeVoid)$where[]='f.is_void=0';
$stmt=db()->prepare("SELECT f.*,o.name office_name,o.code office_code FROM feedback f JOIN offices o ON o.id=f.office_id WHERE ".implode(' AND ',$where)." ORDER BY f.visit_date DESC,f.id DESC");$stmt->execute($params);$rows=$stmt->fetchAll();
if(($_GET['export']??'')==='csv'){$export=[];foreach($rows as $r)$export[]=[$r['id'],$r['office_name'],$r['visit_date'],$r['sex'],$r['age'],$r['client_type'],$r['service_received'],$r['timeliness_rating'],$r['client_handling_rating'],$r['quality_rating'],$r['overall_rating'],$r['average_rating'],$r['comment'],$r['sentiment'],$r['sentiment_confidence'],$r['sentiment_source'],$r['review_status'],$r['final_score'],$r['source'],$r['is_void']?'Void':'Active',$r['submitted_at']];audit((int)$user['id'],'report_csv_export','Admin exported '.count($rows).' filtered feedback rows');csv_download('cityhall-feedback-'.date('Y-m-d').'.csv',['ID','Office','Visit Date','Sex','Age','Client Type','Service','Timeliness','Client Handling','Quality','Overall','Average Rating','Comment','Sentiment','Confidence','Classifier Source','Review Status','Final Score','Record Source','Record Status','Submitted At'],$export);}
$offices=db()->query('SELECT * FROM offices ORDER BY status=\'active\' DESC,name')->fetchAll();$m=dashboard_metrics($officeId?:null,$dateFrom?:null,$dateTo?:null,!$includeArchived,$includeVoid);$ages=age_group_counts($officeId?:null,$dateFrom?:null,$dateTo?:null,!$includeArchived,$includeVoid);$services=service_summary($officeId?:null,10,$dateFrom?:null,$dateTo?:null,!$includeArchived,$includeVoid);
render_dashboard_start('Reports & Export','reports');page_header('Reports & Export','All cards and detailed rows follow the selected office and date range.',$exportPdf?'':'<button type="button" class="btn secondary" data-modal-open="reports-export-modal">Export PDF</button>');
?>
<?php if(!$exportPdf): ?><div class="app-modal" id="reports-export-modal" aria-hidden="true"><section class="app-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="reports-export-title"><button type="button" class="modal-close" data-modal-close>&times;</button><h2 id="reports-export-title">Export Filtered Report</h2><p class="muted">The PDF will include the summary cards, charts, and all <?= count($rows) ?> detailed row(s) matching the active filters.</p><form method="get" target="_blank" class="modal-form"><input type="hidden" name="export" value="pdf"><input type="hidden" name="office_id" value="<?= $officeId ?>"><input type="hidden" name="date_from" value="<?= e($dateFrom) ?>"><input type="hidden" name="date_to" value="<?= e($dateTo) ?>"><?php if($includeArchived):?><input type="hidden" name="include_archived" value="1"><?php endif;?><?php if($includeVoid):?><input type="hidden" name="include_void" value="1"><?php endif;?><div class="formula-box"><strong>Scope:</strong> <?= $officeId?'Selected office':'All offices' ?><br><strong>Date:</strong> <?= e($dateFrom?:'Earliest') ?> to <?= e($dateTo?:'Latest') ?><br><strong>Rows:</strong> <?= count($rows) ?></div><div class="confirm-actions"><button type="button" class="btn secondary" data-modal-close>Cancel</button><button class="btn">Open PDF Preview</button></div></form></section></div><?php endif; ?>
<form class="filters wide" method="get"><select name="office_id"><option value="0">All offices</option><?php foreach($offices as $o):?><option value="<?= (int)$o['id'] ?>" <?= $officeId===(int)$o['id']?'selected':'' ?>><?= e($o['code']) ?> — <?= e($o['name']) ?><?= $o['status']==='archived'?' (Archived)':'' ?></option><?php endforeach;?></select><input type="date" name="date_from" value="<?= e($dateFrom) ?>"><input type="date" name="date_to" value="<?= e($dateTo) ?>"><label class="checkbox-inline"><input type="checkbox" name="include_archived" value="1" <?= $includeArchived?'checked':'' ?>> Include archived offices</label><label class="checkbox-inline"><input type="checkbox" name="include_void" value="1" <?= $includeVoid?'checked':'' ?>> Include void records</label><button class="btn">Generate</button><button class="btn success" name="export" value="csv">Download CSV</button></form>
<div class="stats-grid"><div class="stat-card"><small>Responses</small><strong><?= count($rows) ?></strong></div><div class="stat-card"><small>Average Rating</small><strong><?= number_format($m['avg_rating'],2) ?>/4</strong></div><div class="stat-card"><small>Final Score</small><strong><?= number_format($m['avg_final'],2) ?>%</strong></div><div class="stat-card"><small>Positive Rate</small><strong><?= number_format($m['positive_rate'],1) ?>%</strong></div><div class="stat-card"><small>Action Completion</small><strong><?= number_format($m['completion_rate'],1) ?>%</strong></div></div>
<div class="content-grid"><section class="card"><div class="card-head"><div><h2>Age Groups</h2><p>Current selected scope</p></div></div><div class="chart-box"><canvas data-chart='<?= e(json_encode(array_map(fn($r)=>['label'=>$r['label'],'value'=>(int)$r['count']],$ages))) ?>' data-type="bar"></canvas></div></section><section class="card"><div class="card-head"><div><h2>Most Used Services</h2><p>Response count and average final score</p></div></div><div class="table-wrap"><table><thead><tr><th>Service</th><th>Responses</th><th>Score</th><th>Negative</th></tr></thead><tbody><?php foreach($services as $s):?><tr><td><?= e($s['label']) ?></td><td><?= (int)$s['responses'] ?></td><td><?= number_format((float)$s['avg_score'],2) ?>%</td><td><?= (int)$s['negative_count'] ?></td></tr><?php endforeach;?></tbody></table></div></section></div>
<section class="card"><div class="card-head"><div><h2>Filtered Report</h2><p><?= count($rows) ?> detailed record(s)</p></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Office</th><th>Service</th><th>Client</th><th>Rating</th><th>Sentiment</th><th>Final</th><th>Comment</th></tr></thead><tbody><?php foreach($rows as $r):?><tr class="<?= $r['is_void']?'void-row':'' ?>"><td><?= e($r['visit_date']) ?></td><td><?= e($r['office_code']) ?></td><td><?= e($r['service_received']) ?></td><td><?= e($r['client_type']) ?><br><span class="muted"><?= (int)$r['age'] ?> · <?= e($r['sex']) ?></span></td><td><?= number_format((float)$r['average_rating'],2) ?>/4</td><td><?= badge(status_label($r['sentiment']),$r['sentiment']) ?><br><span class="muted"><?= e($r['review_status']) ?></span></td><td><?= number_format((float)$r['final_score'],2) ?>%</td><td><?= e($r['comment']) ?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="8" class="empty-state">No records for this report range.</td></tr><?php endif;?></tbody></table></div></section>
<?php if($exportPdf):?><script>history.replaceState({},document.title,location.pathname);window.addEventListener('load',()=>setTimeout(()=>window.print(),400));</script><?php endif;?><?php render_dashboard_end(); ?>
