<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_login(['admin']);
$officeId=request_int('office_id');$dateFrom=trim((string)($_GET['date_from']??''));$dateTo=trim((string)($_GET['date_to']??''));
$where=['1=1'];$params=[];if($officeId){$where[]='f.office_id=?';$params[]=$officeId;}if($dateFrom!==''){$where[]='f.visit_date>=?';$params[]=$dateFrom;}if($dateTo!==''){$where[]='f.visit_date<=?';$params[]=$dateTo;}
$stmt=db()->prepare("SELECT f.*,o.name office_name,o.code office_code FROM feedback f JOIN offices o ON o.id=f.office_id WHERE ".implode(' AND ',$where)." ORDER BY f.visit_date DESC");$stmt->execute($params);$rows=$stmt->fetchAll();
if(($_GET['export']??'')==='csv'){
 $export=[];foreach($rows as $r)$export[]=[$r['id'],$r['office_name'],$r['visit_date'],$r['sex'],$r['age'],$r['client_type'],$r['service_received'],$r['timeliness_rating'],$r['client_handling_rating'],$r['quality_rating'],$r['overall_rating'],$r['average_rating'],$r['comment'],$r['sentiment'],$r['sentiment_confidence'],$r['sentiment_source'],$r['final_score'],$r['source'],$r['submitted_at']];
 csv_download('cityhall-feedback-'.date('Y-m-d').'.csv',['ID','Office','Visit Date','Sex','Age','Client Type','Service','Timeliness','Client Handling','Quality','Overall','Average Rating','Comment','Sentiment','Confidence','Classifier Source','Final Score','Record Source','Submitted At'],$export);
}
$offices=db()->query('SELECT * FROM offices ORDER BY name')->fetchAll();$m=dashboard_metrics($officeId?:null);
render_dashboard_start('Reports & Export','reports');page_header('Reports & Export','Generate a print-ready summary or download detailed CSV records.','<button class="btn secondary" onclick="window.print()">Print / Save as PDF</button>');
?>
<form class="filters" method="get"><select name="office_id"><option value="0">All offices</option><?php foreach($offices as $o):?><option value="<?= (int)$o['id'] ?>" <?= $officeId===(int)$o['id']?'selected':'' ?>><?= e($o['code']) ?> — <?= e($o['name']) ?></option><?php endforeach;?></select><input type="date" name="date_from" value="<?= e($dateFrom) ?>"><input type="date" name="date_to" value="<?= e($dateTo) ?>"><button class="btn">Generate</button><button class="btn success" name="export" value="csv">Download CSV</button></form>
<div class="stats-grid"><div class="stat-card"><small>Responses</small><strong><?= $m['total'] ?></strong></div><div class="stat-card"><small>Average Rating</small><strong><?= number_format($m['avg_rating'],2) ?>/4</strong></div><div class="stat-card"><small>Final Score</small><strong><?= number_format($m['avg_final'],2) ?>%</strong></div><div class="stat-card"><small>Positive Rate</small><strong><?= number_format($m['positive_rate'],1) ?>%</strong></div><div class="stat-card"><small>Action Completion</small><strong><?= number_format($m['completion_rate'],1) ?>%</strong></div></div>
<section class="card"><div class="card-head"><div><h2>Filtered Report</h2><p><?= count($rows) ?> detailed record(s)</p></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Office</th><th>Service</th><th>Rating</th><th>Sentiment</th><th>Final Score</th><th>Comment</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?= e($r['visit_date']) ?></td><td><?= e($r['office_code']) ?></td><td><?= e($r['service_received']) ?></td><td><?= number_format((float)$r['average_rating'],2) ?>/4</td><td><?= e(status_label($r['sentiment'])) ?></td><td><?= number_format((float)$r['final_score'],2) ?>%</td><td><?= e($r['comment']) ?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
