<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$admin=require_login(['admin']);
$offices=db()->query("SELECT * FROM offices ORDER BY status='active' DESC,name")->fetchAll();
$selected=request_int('office_id');
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=(string)($_POST['action']??'');$returnOffice=post_int('return_office');
 try{
  if($action==='create'){
   $officeId=post_int('office_id');$name=trim((string)$_POST['full_name']);$username=trim((string)$_POST['username']);$email=trim((string)$_POST['email']);$password=(string)$_POST['password'];
   if(!$officeId||$name===''||$username===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<8||!preg_match('/[A-Za-z]/',$password)||!preg_match('/\d/',$password))throw new RuntimeException('Complete all fields. Password must be at least 8 characters with a letter and a number.');
   $stmt=db()->prepare("INSERT INTO users(office_id,full_name,username,email,password_hash,role,status,created_by_user_id,must_change_password) VALUES(?,?,?,?,?,'office_staff','active',?,1)");$stmt->execute([$officeId,$name,$username,$email,password_hash($password,PASSWORD_DEFAULT),(int)$admin['id']]);audit((int)$admin['id'],'admin_staff_create',"Created staff {$username} for office #{$officeId}");set_flash('success','Staff account created and restricted to the selected office.');
  }elseif($action==='edit'){
   $id=post_int('user_id');$officeId=post_int('office_id');$name=trim((string)$_POST['full_name']);$username=trim((string)$_POST['username']);$email=trim((string)$_POST['email']);$password=(string)($_POST['password']??'');
   $sql=$password!==''?"UPDATE users SET office_id=?,full_name=?,username=?,email=?,password_hash=?,must_change_password=1 WHERE id=? AND role='office_staff'":"UPDATE users SET office_id=?,full_name=?,username=?,email=? WHERE id=? AND role='office_staff'";
   $params=$password!==''?[$officeId,$name,$username,$email,password_hash($password,PASSWORD_DEFAULT),$id]:[$officeId,$name,$username,$email,$id];db()->prepare($sql)->execute($params);audit((int)$admin['id'],'admin_staff_edit',"Updated staff #{$id}; office={$officeId}; password_reset=".($password!==''?'yes':'no'));set_flash('success','Staff account updated.');
  }elseif($action==='status'){
   $id=post_int('user_id');$status=(string)$_POST['status'];if(!in_array($status,['active','archived'],true))throw new RuntimeException('Invalid status.');db()->prepare("UPDATE users SET status=? WHERE id=? AND role='office_staff'")->execute([$status,$id]);audit((int)$admin['id'],'admin_staff_status',"Staff #{$id} -> {$status}");set_flash('success','Staff account status updated.');
  }elseif($action==='delete'){
   $id=post_int('user_id');db()->prepare("DELETE FROM users WHERE id=? AND role='office_staff'")->execute([$id]);audit((int)$admin['id'],'admin_staff_delete',"Deleted staff #{$id}");set_flash('success','Staff account deleted.');
  }
 }catch(Throwable $e){set_flash('error','Unable to complete action: '.$e->getMessage());}
 redirect('admin/staff.php'.($returnOffice?'?office_id='.$returnOffice:''));
}
$where=$selected?'AND u.office_id=?':'';$stmt=db()->prepare("SELECT u.*,o.name office_name,o.code office_code FROM users u JOIN offices o ON o.id=u.office_id WHERE u.role='office_staff' {$where} ORDER BY o.name,u.full_name");$stmt->execute($selected?[$selected]:[]);$staff=$stmt->fetchAll();
render_dashboard_start('Manage Staff','staff');page_header('Manage Staff by Office','Use the office buttons to separate staff accounts. Administrator actions are citywide.');
?>
<div class="tabs"><a class="tab <?= !$selected?'active':'' ?>" href="<?= e(app_url('admin/staff.php')) ?>">All Offices</a><?php foreach($offices as $o):?><a class="tab <?= $selected===(int)$o['id']?'active':'' ?>" href="<?= e(app_url('admin/staff.php?office_id='.$o['id'])) ?>"><?= e($o['code']) ?><?= $o['status']==='archived'?' · Archived':'' ?></a><?php endforeach;?></div>
<div class="split-grid"><section class="panel-form"><h2>Add Office Staff</h2><p>The account can view only feedback and dashboards from its assigned office. It cannot see Manage Staff or CSV Upload.</p><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="create"><input type="hidden" name="return_office" value="<?= $selected ?>"><div class="form-group"><label>Office</label><select name="office_id" required><option value="">Select office</option><?php foreach($offices as $o):?><option value="<?= (int)$o['id'] ?>" <?= $selected===(int)$o['id']?'selected':'' ?>><?= e($o['name']) ?> (<?= e($o['code']) ?>)</option><?php endforeach;?></select></div><div class="form-group"><label>Full Name</label><input name="full_name" required></div><div class="form-row"><div class="form-group"><label>Username</label><input name="username" required></div><div class="form-group"><label>Email</label><input type="email" name="email" required></div></div><div class="form-group"><label>Temporary Password</label><input type="password" name="password" minlength="8" required></div><button class="btn">Create Staff</button></form></section>
<section class="card"><div class="card-head"><div><h2><?= $selected?'Selected Office':'All Office' ?> Staff</h2><p><?= count($staff) ?> account(s)</p></div></div><div class="table-wrap"><table><thead><tr><th>Staff</th><th>Office</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody><?php foreach($staff as $s):?><tr><td><strong><?= e($s['full_name']) ?></strong><br><span class="muted"><?= e($s['username']) ?> · <?= e($s['email']) ?></span></td><td><?= e($s['office_name']) ?><br><span class="muted"><?= e($s['office_code']) ?></span></td><td><?= badge(status_label($s['status']),$s['status']) ?></td><td><?= e(date('M d, Y',strtotime($s['created_at']))) ?></td><td class="actions-cell"><details><summary class="btn secondary small">Edit</summary><form method="post" style="min-width:300px;padding-top:10px"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="edit"><input type="hidden" name="user_id" value="<?= (int)$s['id'] ?>"><input type="hidden" name="return_office" value="<?= $selected ?>"><div class="form-group"><select name="office_id"><?php foreach($offices as $o):?><option value="<?= (int)$o['id'] ?>" <?= (int)$o['id']===(int)$s['office_id']?'selected':'' ?>><?= e($o['name']) ?></option><?php endforeach;?></select></div><div class="form-group"><input name="full_name" value="<?= e($s['full_name']) ?>" required></div><div class="form-group"><input name="username" value="<?= e($s['username']) ?>" required></div><div class="form-group"><input type="email" name="email" value="<?= e($s['email']) ?>" required></div><div class="form-group"><input type="password" name="password" placeholder="New password (optional)"></div><button class="btn small">Save</button></form></details><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="status"><input type="hidden" name="user_id" value="<?= (int)$s['id'] ?>"><input type="hidden" name="return_office" value="<?= $selected ?>"><input type="hidden" name="status" value="<?= $s['status']==='active'?'archived':'active' ?>"><button class="btn <?= $s['status']==='active'?'danger':'success' ?> small"><?= $s['status']==='active'?'Archive':'Reactivate' ?></button></form><form method="post" data-confirm-delete="Permanently delete this staff account?"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="user_id" value="<?= (int)$s['id'] ?>"><input type="hidden" name="return_office" value="<?= $selected ?>"><button class="btn danger small">Delete</button></form></td></tr><?php endforeach;?><?php if(!$staff):?><tr><td colspan="5" class="empty-state">No staff found in this view.</td></tr><?php endif;?></tbody></table></div></section></div>
<?php render_dashboard_end(); ?>
