<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['admin']);
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    if(($_POST['action']??'')==='purge_audit'){
        $eligible=(int)db()->query("SELECT COUNT(*) FROM audit_logs WHERE created_at<DATE_SUB(NOW(),INTERVAL 6 MONTH)")->fetchColumn();
        $stmt=db()->prepare("DELETE FROM audit_logs WHERE created_at<DATE_SUB(NOW(),INTERVAL 6 MONTH)");$stmt->execute();
        audit((int)$user['id'],'audit_logs_purged','Purged '.$stmt->rowCount().' audit record(s) older than six months');
        set_flash('success',$stmt->rowCount().' eligible audit record(s) permanently purged.');redirect('admin/system.php');
    }
}
$q=trim((string)($_GET['q']??''));$actionFilter=trim((string)($_GET['action_filter']??''));$where=['1=1'];$params=[];
if($q!==''){$where[]='(a.details LIKE ? OR a.ip_address LIKE ? OR u.full_name LIKE ?)';array_push($params,"%{$q}%","%{$q}%","%{$q}%");}
if($actionFilter!==''){$where[]='a.action=?';$params[]=$actionFilter;}
$whereSql=implode(' AND ',$where);$perPage=30;
$count=db()->prepare('SELECT COUNT(*) FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE '.$whereSql);$count->execute($params);$p=pagination((int)$count->fetchColumn(),$perPage);
$exportPdf=($_GET['export']??'')==='pdf';$scope=(string)($_GET['scope']??'current');$from=max(1,(int)($_GET['page_from']??$p['page']));$to=max($from,(int)($_GET['page_to']??$from));$from=min($from,$p['pages']);$to=min($to,$p['pages']);
$limit=$p['per_page'];$offset=$p['offset'];
if($exportPdf){if($scope==='all'){$limit=$p['total'];$offset=0;}elseif($scope==='custom'){$offset=($from-1)*$perPage;$limit=($to-$from+1)*$perPage;}else{$offset=($from-1)*$perPage;}}
$stmt=db()->prepare("SELECT a.*,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE {$whereSql} ORDER BY a.created_at DESC LIMIT ".max(1,$limit).' OFFSET '.$offset);$stmt->execute($params);$logs=$stmt->fetchAll();
$eligiblePurge=(int)db()->query("SELECT COUNT(*) FROM audit_logs WHERE created_at<DATE_SUB(NOW(),INTERVAL 6 MONTH)")->fetchColumn();
$modelFile=__DIR__.'/../ml/models/svm_sentiment.joblib';$metricsFile=__DIR__.'/../ml/models/model_metrics.json';$metrics=is_file($metricsFile)?json_decode((string)file_get_contents($metricsFile),true):null;$health=predict_sentiment('Mabilis at maayos ang serbisyo.');
$counts=['active_offices'=>(int)db()->query("SELECT COUNT(*) FROM offices WHERE status='active'")->fetchColumn(),'reviews'=>(int)db()->query("SELECT COUNT(*) FROM feedback WHERE review_status='needs_review' AND is_void=0")->fetchColumn(),'training'=>(int)db()->query('SELECT COUNT(*) FROM training_candidates')->fetchColumn(),'locked'=>(int)db()->query('SELECT COUNT(*) FROM users WHERE locked_until>NOW()')->fetchColumn()];$actions=db()->query('SELECT DISTINCT action FROM audit_logs ORDER BY action')->fetchAll(PDO::FETCH_COLUMN);
render_dashboard_start($exportPdf?'Audit Log Report':'System & Audit','system');page_header('System Health & Audit','Verify the live SVM bridge, security state, backups, and protected activity.',$exportPdf?'':'<a class="btn" href="'.e(app_url('admin/backup.php')).'">Download SQL Backup</a>');
?>
<?php if(!$exportPdf): ?><div class="app-modal" id="audit-export-modal" aria-hidden="true"><section class="app-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="audit-export-title"><button type="button" class="modal-close" data-modal-close>&times;</button><h2 id="audit-export-title">Export Audit Log PDF</h2><p class="muted">Active search and action filters will be preserved.</p><form method="get" target="_blank" class="modal-form"><input type="hidden" name="export" value="pdf"><?php if($q!==''):?><input type="hidden" name="q" value="<?= e($q) ?>"><?php endif;?><?php if($actionFilter!==''):?><input type="hidden" name="action_filter" value="<?= e($actionFilter) ?>"><?php endif;?><div class="scope-options"><label class="scope-option"><input type="radio" name="scope" value="current" checked><span><strong>Current page</strong><br><small>Page <?= $p['page'] ?> only.</small></span></label><label class="scope-option"><input type="radio" name="scope" value="custom"><span><strong>Custom page range</strong><br><small>Choose the first and last page below.</small></span></label><label class="scope-option"><input type="radio" name="scope" value="all"><span><strong>All filtered pages</strong><br><small>All <?= $p['total'] ?> matching events.</small></span></label></div><div class="page-range"><label>From page<input type="number" name="page_from" min="1" max="<?= $p['pages'] ?>" value="<?= $p['page'] ?>"></label><label>To page<input type="number" name="page_to" min="1" max="<?= $p['pages'] ?>" value="<?= $p['page'] ?>"></label></div><div class="confirm-actions"><button type="button" class="btn secondary" data-modal-close>Cancel</button><button class="btn">Open PDF Preview</button></div></form></section></div>
<div class="app-modal" id="audit-purge-modal" aria-hidden="true"><section class="app-modal-dialog" role="alertdialog" aria-modal="true"><button type="button" class="modal-close" data-modal-close>&times;</button><h2>Purge Old Audit Logs</h2><p>Only logs older than six months are eligible. This will permanently delete <strong><?= $eligiblePurge ?></strong> record(s); recent logs remain protected.</p><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="purge_audit"><div class="confirm-actions"><button type="button" class="btn secondary" data-modal-close>Cancel</button><button class="btn danger" <?= $eligiblePurge===0?'disabled':'' ?>>Purge Eligible Logs</button></div></form></section></div><?php endif; ?>
<div class="stats-grid"><div class="stat-card"><small>Database</small><strong>Connected</strong><span>pasig_feedback_portal</span></div><div class="stat-card"><small>SVM Bridge</small><strong><?= $health['source']==='svm'?'Working':'Fallback' ?></strong><span><?= e($health['label']) ?> · <?= number_format((float)$health['confidence']*100,1) ?>%</span></div><div class="stat-card"><small>Active Offices</small><strong><?= $counts['active_offices'] ?></strong></div><div class="stat-card"><small>Review Queue</small><strong><?= $counts['reviews'] ?></strong></div><div class="stat-card"><small>Locked Accounts</small><strong><?= $counts['locked'] ?></strong></div></div>
<?php if(!$exportPdf): ?><div class="content-grid"><section class="card"><div class="card-head"><div><h2>SVM Model Information</h2><p>Live path and development metrics</p></div></div><div class="formula-box"><strong>Python:</strong> <?= e(PYTHON_BIN) ?><br><strong>Model:</strong> <?= is_file($modelFile)?'Ready':'Missing' ?><br><strong>Live source:</strong> <?= e($health['source']) ?><br><strong>Model version:</strong> <?= e(model_version()) ?></div><?php if($metrics):?><p><strong>Samples:</strong> <?= (int)$metrics['sample_count'] ?> · <strong>Accuracy:</strong> <?= number_format((float)$metrics['accuracy']*100,2) ?>%</p><?php endif;?></section><section class="card"><div class="card-head"><div><h2>Security & Governance</h2></div></div><div class="bar-list"><div>✓ Five-attempt account lockout</div><div>✓ CSRF, prepared SQL, escaping, and protected audit logs</div><div>✓ Audit retention: purge restricted to records older than six months</div><div>✓ <?= $counts['training'] ?> approved retraining candidate(s)</div></div></section></div><?php endif; ?>
<section class="card"><div class="card-head"><div><h2><?= $exportPdf?'Audit Log Export':'Recent Audit Log' ?></h2><p><?= $exportPdf?count($logs):$p['total'] ?> event(s) shown</p></div><?php if(!$exportPdf):?><div class="actions-cell"><button type="button" class="btn secondary small" data-modal-open="audit-export-modal">Export PDF</button><button type="button" class="btn danger small" data-modal-open="audit-purge-modal" <?= $eligiblePurge===0?'disabled':'' ?>>Purge Old Logs (<?= $eligiblePurge ?>)</button></div><?php endif;?></div><?php if(!$exportPdf):?><form class="filters compact" method="get"><input name="q" value="<?= e($q) ?>" placeholder="Search user, detail, IP"><select name="action_filter"><option value="">All actions</option><?php foreach($actions as $a):?><option value="<?= e($a) ?>" <?= $actionFilter===$a?'selected':'' ?>><?= e(status_label($a)) ?></option><?php endforeach;?></select><button class="btn">Apply</button></form><?php endif;?><div class="table-wrap"><table><thead><tr><th>Date</th><th>User</th><th>Action</th><th>Details</th><th>IP</th></tr></thead><tbody><?php foreach($logs as $l):?><tr><td><?= e(date('M d, Y h:i A',strtotime($l['created_at']))) ?></td><td><?= e($l['full_name']?:'Public/System') ?></td><td><?= e(status_label($l['action'])) ?></td><td><?= e($l['details']) ?></td><td><?= e($l['ip_address']) ?></td></tr><?php endforeach;?><?php if(!$logs):?><tr><td colspan="5" class="empty-state">No audit records match the filters.</td></tr><?php endif;?></tbody></table></div><?php if(!$exportPdf):?><?= pagination_links($p) ?><?php endif;?></section>
<?php if($exportPdf):?><script>history.replaceState({},document.title,location.pathname);window.addEventListener('load',()=>setTimeout(()=>window.print(),400));</script><?php endif;?>
<?php render_dashboard_end(); ?>
