<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_login(['admin']);
$modelFile=__DIR__.'/../ml/models/svm_sentiment.joblib';$metricsFile=__DIR__.'/../ml/models/model_metrics.json';$metrics=is_file($metricsFile)?json_decode((string)file_get_contents($metricsFile),true):null;
$logs=db()->query("SELECT a.*,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 200")->fetchAll();
$counts=['offices'=>(int)db()->query('SELECT COUNT(*) FROM offices')->fetchColumn(),'users'=>(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn(),'feedback'=>(int)db()->query('SELECT COUNT(*) FROM feedback')->fetchColumn(),'actions'=>(int)db()->query('SELECT COUNT(*) FROM actions')->fetchColumn()];
render_dashboard_start('System & Audit','system');page_header('System Health & Audit','Verify core components and review the latest protected system activity.');
?>
<div class="stats-grid"><div class="stat-card"><small>Database</small><strong>Connected</strong><span>pasig_feedback_portal</span></div><div class="stat-card"><small>SVM Model</small><strong><?= is_file($modelFile)?'Ready':'Missing' ?></strong><span><?= is_file($modelFile)?number_format(filesize($modelFile)/1024,1).' KB':'Run ml/train.py' ?></span></div><div class="stat-card"><small>Offices</small><strong><?= $counts['offices'] ?></strong></div><div class="stat-card"><small>Users</small><strong><?= $counts['users'] ?></strong></div><div class="stat-card"><small>Feedback</small><strong><?= $counts['feedback'] ?></strong></div></div>
<div class="content-grid"><section class="card"><div class="card-head"><div><h2>Demo Model Information</h2><p>Development verification only—not the final research result</p></div></div><?php if($metrics):?><div class="formula-box"><strong>Sample rows:</strong> <?= (int)$metrics['sample_count'] ?><br><strong>Holdout accuracy:</strong> <?= number_format((float)$metrics['accuracy']*100,2) ?>%<br><strong>Method:</strong> TF-IDF word/character features + LinearSVC</div><p class="help"><?= e($metrics['warning']??'') ?></p><?php else:?><div class="error-box">Model metrics file is missing. Run python ml/train.py.</div><?php endif;?></section><section class="card"><div class="card-head"><div><h2>Built-in Safeguards</h2><p>Implemented in the supplied source code</p></div></div><div class="bar-list"><div>✓ Password hashing and active/archive login checks</div><div>✓ Role-based and office-scoped authorization</div><div>✓ Prepared SQL statements and CSRF tokens</div><div>✓ Required comments and rating validation</div><div>✓ Audit logs and CSV import history</div><div>✓ De-identification reminder for historical comments</div></div></section></div>
<section class="card"><div class="card-head"><div><h2>Recent Audit Log</h2><p>Latest 200 login, management, import, and workflow events</p></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>User</th><th>Action</th><th>Details</th><th>IP</th></tr></thead><tbody><?php foreach($logs as $l):?><tr><td><?= e(date('M d, Y h:i A',strtotime($l['created_at']))) ?></td><td><?= e($l['full_name']?:'Public/System') ?></td><td><?= e(status_label($l['action'])) ?></td><td><?= e($l['details']) ?></td><td><?= e($l['ip_address']) ?></td></tr><?php endforeach;?><?php if(!$logs):?><tr><td colspan="5" class="empty-state">No audit records yet.</td></tr><?php endif;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
