<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['office_head','supervisor']);$officeId=(int)$user['office_id'];$isHead=$user['role']==='office_head';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$id=post_int('action_id');$requested=(string)($_POST['status']??'');$notes=trim((string)($_POST['resolution_notes']??''));
 $stmt=db()->prepare('SELECT * FROM actions WHERE id=? AND office_id=?');$stmt->execute([$id,$officeId]);$row=$stmt->fetch();
 try{
  if(!$row)throw new RuntimeException('Action item not found in your office.');if(!$isHead&&in_array($row['status'],['pending_approval','completed'],true))throw new RuntimeException('Only the Office Head can change an action that is pending approval or completed.');if(mb_strlen($notes)<5)throw new RuntimeException('Enter review or resolution notes.');
  if($isHead && $requested==='completed'){
   db()->prepare("UPDATE actions SET status='completed',resolution_notes=?,approved_by_user_id=?,approved_at=NOW(),completed_at=NOW() WHERE id=? AND office_id=?")->execute([$notes,(int)$user['id'],$id,$officeId]);
   if($row['completion_requested_by_user_id'])send_notification((int)$row['completion_requested_by_user_id'],$officeId,'approval','Completion approved','Your completion request for action #'.$id.' was approved.','office/actions.php');audit((int)$user['id'],'action_approve',"Action #{$id} completed by Office Head");notify_admins('action','Action completed',$user['office_code'].' completed action #'.$id.'.','admin/actions.php');set_flash('success','Action completed and approved.');
  }elseif(!$isHead && $requested==='completed'){
   db()->prepare("UPDATE actions SET status='pending_approval',resolution_notes=?,completion_requested_by_user_id=?,completion_requested_at=NOW(),completed_at=NULL WHERE id=? AND office_id=?")->execute([$notes,(int)$user['id'],$id,$officeId]);
   notify_office_heads($officeId,'approval','Completion approval required','A Supervisor requested completion of action #'.$id.'.','office/actions.php');audit((int)$user['id'],'action_completion_request',"Action #{$id} submitted by Supervisor for head approval");set_flash('success','Completion submitted to the Office Head for approval.');
  }elseif(in_array($requested,['needs_action','in_progress'],true)){
   db()->prepare("UPDATE actions SET status=?,resolution_notes=?,completion_requested_by_user_id=NULL,completion_requested_at=NULL,approved_by_user_id=NULL,approved_at=NULL,completed_at=NULL WHERE id=? AND office_id=?")->execute([$requested,$notes,$id,$officeId]);
   audit((int)$user['id'],'action_update',"Action #{$id} -> {$requested}");set_flash('success','Action status updated.');
  }elseif($isHead && $requested==='reject_completion'){
   db()->prepare("UPDATE actions SET status='in_progress',resolution_notes=?,completion_requested_by_user_id=NULL,completion_requested_at=NULL WHERE id=? AND office_id=?")->execute([$notes,$id,$officeId]);
   if($row['completion_requested_by_user_id'])send_notification((int)$row['completion_requested_by_user_id'],$officeId,'approval','Completion request returned','Action #'.$id.' needs more work.','office/actions.php');
   audit((int)$user['id'],'action_completion_rejected',"Action #{$id} returned to in progress");set_flash('success','Completion request returned to In Progress.');
  }else throw new RuntimeException('Invalid status transition.');
 }catch(Throwable $e){set_flash('error',$e->getMessage());}
 redirect('office/actions.php');
}
$status=trim((string)($_GET['status']??''));$q=trim((string)($_GET['q']??''));$where=['a.office_id=?'];$params=[$officeId];if(in_array($status,['needs_action','in_progress','pending_approval','completed'],true)){$where[]='a.status=?';$params[]=$status;}if($q!==''){$where[]='(a.title LIKE ? OR a.details LIKE ? OR a.resolution_notes LIKE ? OR CAST(a.id AS CHAR)=?)';$params[]="%{$q}%";$params[]="%{$q}%";$params[]="%{$q}%";$params[]=$q;}
$count=db()->prepare('SELECT COUNT(*) FROM actions a WHERE '.implode(' AND ',$where));$count->execute($params);$p=pagination((int)$count->fetchColumn(),20);$stmt=db()->prepare("SELECT a.*,f.sentiment,f.final_score,f.comment,u.full_name requester_name FROM actions a LEFT JOIN feedback f ON f.id=a.feedback_id LEFT JOIN users u ON u.id=a.completion_requested_by_user_id WHERE ".implode(' AND ',$where)." ORDER BY FIELD(a.status,'pending_approval','needs_action','in_progress','completed'),a.updated_at DESC LIMIT {$p['per_page']} OFFSET {$p['offset']}");$stmt->execute($params);$rows=$stmt->fetchAll();
render_dashboard_start('Action Management','actions');page_header($user['office_code'].' Action Management',$isHead?'Manage concerns and approve final completion requests from Supervisors.':'Manage concerns and submit completed actions to your Office Head for approval.');
?>
<div class="tabs"><a class="tab <?= $status===''?'active':'' ?>" href="?">All</a><?php foreach(['needs_action','in_progress','pending_approval','completed'] as $v):?><a class="tab <?= $status===$v?'active':'' ?>" href="?status=<?= e($v) ?>"><?= e(status_label($v)) ?></a><?php endforeach;?></div><form class="filters compact" method="get"><input name="q" value="<?= e($q) ?>" placeholder="Search action ID, title, notes"><select name="status"><option value="">All statuses</option><?php foreach(['needs_action','in_progress','pending_approval','completed'] as $v):?><option value="<?= $v ?>" <?= $status===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><button class="btn">Apply</button></form>
<section class="card"><div class="table-wrap"><table><thead><tr><th>Action</th><th>Source Feedback</th><th>Status</th><th>Workflow Update</th><th>Age</th></tr></thead><tbody><?php foreach($rows as $a):?><tr><td><strong>#<?= (int)$a['id'] ?> · <?= e($a['title']) ?></strong><p class="muted"><?= e($a['details']) ?></p></td><td><?= $a['feedback_id']?'#'.(int)$a['feedback_id']:'Manual' ?><?php if($a['sentiment']): ?><br><?= badge(status_label($a['sentiment']),$a['sentiment']) ?> · <?= number_format((float)$a['final_score'],2) ?>%<?php endif; ?></td><td><?= badge(status_label($a['status']),$a['status']) ?><?php if($a['requester_name']): ?><br><span class="muted">Requested by <?= e($a['requester_name']) ?></span><?php endif; ?></td><td><?php if(!$isHead&&in_array($a['status'],['pending_approval','completed'],true)): ?><div class="formula-box"><?= $a['status']==='pending_approval'?'Waiting for Office Head approval.':'Completed and approved by the Office Head.' ?></div><?php else: ?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action_id" value="<?= (int)$a['id'] ?>"><select name="status"><?php if($a['status']==='pending_approval'&&$isHead): ?><option value="completed">Approve Completion</option><option value="reject_completion">Return to In Progress</option><?php else: ?><option value="needs_action" <?= $a['status']==='needs_action'?'selected':'' ?>>Needs Action</option><option value="in_progress" <?= $a['status']==='in_progress'?'selected':'' ?>>In Progress</option><option value="completed"><?= $isHead?'Complete & Approve':'Request Completion' ?></option><?php endif; ?></select><textarea name="resolution_notes" placeholder="Required review or resolution notes" required><?= e($a['resolution_notes']) ?></textarea><button class="btn small">Save</button></form><?php endif; ?></td><td><?= round((time()-strtotime($a['created_at']))/86400,1) ?> day(s)<br><span class="muted">Updated <?= e(date('M d, Y h:i A',strtotime($a['updated_at']))) ?></span></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="5" class="empty-state">No action items.</td></tr><?php endif;?></tbody></table></div><?= pagination_links($p) ?></section>
<script>document.querySelectorAll('textarea[name="resolution_notes"]').forEach((field) => { field.value = ''; });</script>
<?php render_dashboard_end(); ?>
