<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['office_head','office_staff']);$officeId=(int)$user['office_id'];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$id=post_int('action_id');$status=(string)($_POST['status']??'');$notes=trim((string)($_POST['resolution_notes']??''));if(in_array($status,['needs_action','in_progress','completed'],true)){if($notes===''){set_flash('error','Enter review or resolution notes before saving the action.');redirect('office/actions.php');}$completed=$status==='completed'?date('Y-m-d H:i:s'):null;$stmt=db()->prepare('UPDATE actions SET status=?,resolution_notes=?,completed_at=?,assigned_to_user_id=? WHERE id=? AND office_id=?');$stmt->execute([$status,$notes,$completed,(int)$user['id'],$id,$officeId]);audit((int)$user['id'],'office_action_update',"Action #{$id} -> {$status}");set_flash('success','Action item updated.');}redirect('office/actions.php');}
$status=trim((string)($_GET['status']??''));$params=[$officeId];$statusSql='';if(in_array($status,['needs_action','in_progress','completed'],true)){$statusSql='AND a.status=?';$params[]=$status;}$stmt=db()->prepare("SELECT a.*,f.comment,f.final_score,f.sentiment,u.full_name assigned_name FROM actions a LEFT JOIN feedback f ON f.id=a.feedback_id LEFT JOIN users u ON u.id=a.assigned_to_user_id WHERE a.office_id=? {$statusSql} ORDER BY FIELD(a.status,'needs_action','in_progress','completed'),a.updated_at DESC");$stmt->execute($params);$rows=$stmt->fetchAll();
render_dashboard_start('Action Management','actions');page_header($user['office_code'].' Action Management','Review concerns and move each item from Needs Action to In Progress and Completed.');
?>
<div class="tabs"><a class="tab <?= $status===''?'active':'' ?>" href="?">All</a><?php foreach(['needs_action','in_progress','completed'] as $v):?><a class="tab <?= $status===$v?'active':'' ?>" href="?status=<?= $v ?>"><?= e(status_label($v)) ?></a><?php endforeach;?></div>
<section class="card"><div class="table-wrap"><table><thead><tr><th>Concern</th><th>Feedback Result</th><th>Workflow</th><th>Last Update</th></tr></thead><tbody><?php foreach($rows as $a):?><tr id="action-<?= (int)$a['id'] ?>"><td><strong><?= e($a['title']) ?></strong><br><span class="muted"><?= e($a['details']) ?></span></td><td><?= $a['sentiment']?badge(status_label($a['sentiment']),$a['sentiment']):'' ?><br><strong><?= $a['final_score']!==null?number_format((float)$a['final_score'],2).'%':'' ?></strong></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action_id" value="<?= (int)$a['id'] ?>"><div class="form-group"><select name="status"><?php foreach(['needs_action','in_progress','completed'] as $v):?><option value="<?= $v ?>" <?= $a['status']===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select></div><div class="form-group"><textarea name="resolution_notes" placeholder="Required review or resolution notes" required><?= e($a['resolution_notes']) ?></textarea></div><button class="btn small">Save Update</button></form></td><td><?= e(date('M d, Y h:i A',strtotime($a['updated_at']))) ?><br><span class="muted"><?= e($a['assigned_name']?:'Unassigned') ?></span></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="4" class="empty-state">No action items in this view.</td></tr><?php endif;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
