<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['office_head','supervisor','office_staff']);$officeId=(int)$user['office_id'];
$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));$staff=trim((string)($_GET['assisted_by']??''));
$options=assisting_staff_options($officeId,$from?:null,$to?:null);$rows=client_output_rows($officeId,$from?:null,$to?:null,$staff);
$total=array_sum(array_column($rows,'client_count'));$days=count($rows);$peak=$rows?max(array_column($rows,'client_count')):0;$avg=$days?$total/$days:0;
render_dashboard_start('Client Output','client_output');page_header('Client Output','Daily catered-client volume for '.$user['office_name'].'.');
?>
<form class="filters wide" method="get"><label class="filter-field"><span>Start date</span><input type="date" name="from" value="<?= e($from) ?>"></label><label class="filter-field"><span>End date</span><input type="date" name="to" value="<?= e($to) ?>"></label><select name="assisted_by"><option value="">All Staff (Assisted By)</option><?php foreach($options as $option): ?><option value="<?= e($option['label']) ?>" <?= $staff===$option['label']?'selected':'' ?>><?= e($option['label']) ?> · <?= (int)$option['clients'] ?> clients</option><?php endforeach; ?></select><button class="btn">Apply Filters</button></form>
<div class="stats-grid"><div class="stat-card highlight"><small>Total Output</small><strong><?= (int)$total ?></strong><span>client feedback records</span></div><div class="stat-card"><small>Average Daily Output</small><strong><?= number_format($avg,1) ?></strong><span>clients / active day</span></div><div class="stat-card"><small>Peak Daily Output</small><strong><?= (int)$peak ?></strong><span>clients</span></div><div class="stat-card"><small>Active Days</small><strong><?= $days ?></strong><span>within selected range</span></div></div>
<section class="card"><div class="card-head"><div><h2>Daily Output Breakdown</h2><p>Completed feedback records per service date.</p></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Daily Output</th><th>Volume vs. Peak</th><th>Average Rating</th><th>Assisted By</th></tr></thead><tbody><?php foreach($rows as $row): $width=$peak?(int)round(((int)$row['client_count']/$peak)*100):0; ?><tr><td><?= e(date('M d, Y',strtotime($row['visit_date']))) ?></td><td><?= badge((string)$row['client_count'].' clients','positive') ?></td><td><div class="bar-track"><div class="bar-fill" style="width:<?= $width ?>%"></div></div><small class="muted"><?= $width ?>%</small></td><td><?= number_format((float)$row['avg_rating'],2) ?>/4</td><td><?= e($row['top_assisting_staff']) ?></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="5" class="empty-state">No client output matches the selected filters.</td></tr><?php endif; ?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
