<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['office_head','office_staff']);$officeId=(int)$user['office_id'];$m=dashboard_metrics($officeId);$trend=monthly_trend($officeId);$indicators=indicator_averages($officeId);$recent=recent_feedback($officeId);$sex=demographic_counts($officeId,'sex');$client=demographic_counts($officeId,'client_type');$ages=age_group_counts($officeId);$services=service_summary($officeId,8);$terms=frequent_concern_terms($officeId);render_dashboard_start('Office Overview','overview');page_header($user['office_code'].' Office Overview','Only feedback, actions, and analytics assigned to '.$user['office_name'].' are visible.',$user['role']==='office_head'?'<a class="btn" href="'.e(app_url('office/data.php')).'">Import Historical CSV</a>':'');
?>
<div class="stats-grid"><div class="stat-card highlight"><small>Responses</small><strong><?= $m['total'] ?></strong><span>Non-void office records</span></div><div class="stat-card"><small>Final Satisfaction</small><strong><?= number_format($m['avg_final'],1) ?>%</strong><span><?= e(final_interpretation($m['avg_final'])) ?></span></div><div class="stat-card"><small>Average Rating</small><strong><?= number_format($m['avg_rating'],2) ?>/4</strong></div><div class="stat-card"><small>Needs Review</small><strong><?= $m['review_count'] ?></strong><span><?= $m['fallback_count'] ?> fallback result(s)</span></div><div class="stat-card"><small>Actions</small><strong><?= $m['needs_action'] ?></strong><span><?= $m['pending_approval'] ?> pending approval</span></div></div>
<div class="content-grid"><section class="card"><div class="card-head"><div><h2>Six-Month Trend</h2></div></div><div class="chart-box"><canvas data-chart='<?= e(json_encode($trend)) ?>' data-type="line"></canvas></div></section><section class="card"><div class="card-head"><div><h2>Sentiment Distribution</h2></div></div><div class="sentiment-stack"><div class="sentiment-box positive"><strong><?= $m['positive'] ?></strong><span>Positive</span></div><div class="sentiment-box neutral"><strong><?= $m['neutral'] ?></strong><span>Neutral</span></div><div class="sentiment-box negative"><strong><?= $m['negative'] ?></strong><span>Negative</span></div></div><h2 style="margin-top:24px">Indicator Averages</h2><div class="bar-list"><?php foreach($indicators as $label=>$value):?><div class="bar-row"><span><?= e($label) ?></span><div class="bar-track"><div class="bar-fill" style="width:<?= min(100,($value/4)*100) ?>%"></div></div><b><?= number_format($value,2) ?></b></div><?php endforeach;?></div></section></div>
<div class="content-grid"><section class="card"><div class="card-head"><div><h2>Demographics</h2></div></div><div class="demographic-grid"><div><h3>Sex</h3><?php foreach($sex as $r):?><p><?= e($r['label']) ?> <strong><?= (int)$r['count'] ?></strong></p><?php endforeach;?></div><div><h3>Client Type</h3><?php foreach($client as $r):?><p><?= e($r['label']) ?> <strong><?= (int)$r['count'] ?></strong></p><?php endforeach;?></div><div><h3>Age Groups</h3><?php foreach($ages as $r):?><p><?= e($r['label']) ?> <strong><?= (int)$r['count'] ?></strong></p><?php endforeach;?></div></div></section><section class="card"><div class="card-head"><div><h2>Service Performance</h2></div></div><div class="table-wrap"><table><thead><tr><th>Service</th><th>Responses</th><th>Score</th></tr></thead><tbody><?php foreach($services as $s):?><tr><td><?= e($s['label']) ?></td><td><?= (int)$s['responses'] ?></td><td><?= number_format((float)$s['avg_score'],1) ?>%</td></tr><?php endforeach;?></tbody></table></div></section></div>
<section class="card" style="margin-bottom:16px"><div class="card-head"><div><h2>Frequent Concern Terms</h2><p>Common words from this office's negative feedback.</p></div></div><div class="word-cloud"><?php foreach($terms as $t): ?><span style="font-size:<?= min(28,12+(int)$t['count']*2) ?>px"><?= e($t['term']) ?><small><?= (int)$t['count'] ?></small></span><?php endforeach; ?><?php if(!$terms): ?><div class="empty-state">No negative-comment terms yet.</div><?php endif; ?></div></section>
<section class="card"><div class="card-head"><div><h2>Recent Office Feedback</h2></div><a class="btn secondary small" href="<?= e(app_url('office/feedback.php')) ?>">View all</a></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Service</th><th>Sentiment</th><th>Review</th><th>Final Score</th><th>Comment</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?= e($r['visit_date']) ?></td><td><?= e($r['service_received']) ?></td><td><?= badge(status_label($r['sentiment']),$r['sentiment']) ?></td><td><?= e(status_label($r['review_status'])) ?></td><td><?= number_format((float)$r['final_score'],2) ?>%</td><td><?= e(mb_strimwidth($r['comment'],0,120,'…')) ?></td></tr><?php endforeach;?><?php if(!$recent):?><tr><td colspan="6" class="empty-state">No feedback yet.</td></tr><?php endif;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
