<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['office_head','office_staff']);
render_dashboard_start('Office Overview','overview');
$officeId=(int)$user['office_id'];$m=dashboard_metrics($officeId);$trend=monthly_trend($officeId);$indicators=indicator_averages($officeId);$recent=recent_feedback($officeId);$sex=demographic_counts($officeId,'sex');$clientTypes=demographic_counts($officeId,'client_type');
$actions=$user['role']==='office_head'?'<a class="btn" href="'.e(app_url('office/data.php')).'">Import Historical CSV</a>':'<a class="btn secondary" href="'.e(app_url('office/reports.php')).'">Open Reports</a>';
page_header($user['office_name'].' Overview','All metrics and records on this page are restricted to '.$user['office_code'].' only.',$actions);
?>
<div class="stats-grid"><div class="stat-card highlight"><small>Total Responses</small><strong><?= $m['total'] ?></strong><span><?= e($user['office_code']) ?> only</span></div><div class="stat-card"><small>Final Satisfaction</small><strong><?= number_format($m['avg_final'],1) ?>%</strong><span><?= e(final_interpretation($m['avg_final'])) ?></span></div><div class="stat-card"><small>Average Rating</small><strong><?= number_format($m['avg_rating'],2) ?>/4</strong><span>Structured ratings</span></div><div class="stat-card"><small>Positive Sentiment</small><strong><?= number_format($m['positive_rate'],1) ?>%</strong><span><?= $m['positive'] ?> positive</span></div><div class="stat-card"><small>Open Actions</small><strong><?= $m['needs_action']+$m['in_progress'] ?></strong><span><?= $m['completion_rate'] ?>% completed</span></div></div>
<div class="content-grid"><section class="card"><div class="card-head"><div><h2>Six-Month Trend</h2><p>Average final weighted satisfaction score</p></div></div><div class="chart-box"><canvas data-chart='<?= e(json_encode($trend)) ?>' data-type="line"></canvas></div></section><section class="card"><div class="card-head"><div><h2>SVM Sentiment</h2><p>Required comment classification</p></div></div><div class="sentiment-stack"><div class="sentiment-box positive"><strong><?= $m['positive'] ?></strong><span>Positive</span></div><div class="sentiment-box neutral"><strong><?= $m['neutral'] ?></strong><span>Neutral</span></div><div class="sentiment-box negative"><strong><?= $m['negative'] ?></strong><span>Negative</span></div></div><h2 style="margin-top:22px">Service Indicators</h2><div class="bar-list"><?php foreach($indicators as $label=>$value):?><div class="bar-row"><span><?= e($label) ?></span><div class="bar-track"><div class="bar-fill" style="width:<?= min(100,($value/4)*100) ?>%"></div></div><b><?= number_format($value,2) ?></b></div><?php endforeach;?></div></section></div>
<div class="content-grid"><section class="card"><div class="card-head"><div><h2>Client Demographics</h2><p>Sex and client classification</p></div></div><h3>Sex</h3><div class="bar-list"><?php $max=max(1,...array_map(fn($x)=>(int)$x['count'],$sex));foreach($sex as $r):?><div class="bar-row"><span><?= e($r['label']) ?></span><div class="bar-track"><div class="bar-fill" style="width:<?= ((int)$r['count']/$max)*100 ?>%"></div></div><b><?= (int)$r['count'] ?></b></div><?php endforeach;?></div><h3 style="margin-top:22px">Client Type</h3><div class="bar-list"><?php $max=max(1,...array_map(fn($x)=>(int)$x['count'],$clientTypes));foreach($clientTypes as $r):?><div class="bar-row"><span><?= e($r['label']) ?></span><div class="bar-track"><div class="bar-fill" style="width:<?= ((int)$r['count']/$max)*100 ?>%"></div></div><b><?= (int)$r['count'] ?></b></div><?php endforeach;?></div></section><section class="card"><div class="card-head"><div><h2>Scoring Method</h2><p>Applied to every feedback response</p></div></div><div class="formula-box"><strong>Final Score = (Rating % × 60%) + (Sentiment Score × 40%)</strong><br><br>Rating % = average of four 1–4 ratings ÷ 4 × 100.<br>Sentiment score: Positive = 100, Neutral = 50, Negative = 0.</div><p class="help">The SVM prediction supports monitoring but should not be the sole basis for disciplinary decisions. Review the original comment and context.</p></section></div>
<section class="card"><div class="card-head"><div><h2>Recent Office Feedback</h2><p>Latest <?= e($user['office_code']) ?> records</p></div><a class="btn secondary small" href="<?= e(app_url('office/feedback.php')) ?>">View all</a></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Service</th><th>Client</th><th>Sentiment</th><th>Final</th><th>Comment</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?= e(date('M d, Y',strtotime($r['visit_date']))) ?></td><td><?= e($r['service_received']) ?></td><td><?= e($r['client_type']) ?></td><td><?= badge(status_label($r['sentiment']),$r['sentiment']) ?></td><td><?= number_format((float)$r['final_score'],2) ?>%</td><td><?= e(mb_strimwidth($r['comment'],0,110,'…')) ?></td></tr><?php endforeach;?><?php if(!$recent):?><tr><td colspan="6" class="empty-state">No feedback yet.</td></tr><?php endif;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
