<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['office_head']);$officeId=(int)$user['office_id'];

function csv_value(array $row,array $map,array $aliases): string{
 foreach($aliases as $alias){if(isset($map[$alias]))return trim((string)($row[$map[$alias]]??''));}
 return '';
}

if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=(string)($_POST['action']??'');
 try{
  if($action==='manual'){
   $visitDate=(string)$_POST['visit_date'];$sex=(string)$_POST['sex'];$age=(int)$_POST['age'];$clientType=(string)$_POST['client_type'];$service=trim((string)$_POST['service_received']);$comment=trim((string)$_POST['comment']);$ratings=[(int)$_POST['timeliness'],(int)$_POST['client_handling'],(int)$_POST['quality'],(int)$_POST['overall']];
   if(strtotime($visitDate)===false||$visitDate>date('Y-m-d')||!in_array($sex,['Female','Male','Prefer not to say'],true)||$age<1||$age>120||!in_array($clientType,['Pasigueño','Non-Pasigueño','City Government Employee'],true)||$service===''||mb_strlen($comment)<5||array_filter($ratings,fn($r)=>!valid_rating($r)))throw new RuntimeException('Complete all fields with valid values.');
   $prediction=predict_sentiment($comment);$scores=compute_feedback_scores($ratings,$prediction['label']);
   $stmt=db()->prepare("INSERT INTO feedback(office_id,visit_date,sex,age,client_type,service_received,timeliness_rating,client_handling_rating,quality_rating,overall_rating,comment,sentiment,sentiment_confidence,sentiment_source,average_rating,rating_percent,comment_score,final_score,source,imported_by_user_id,submitted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'manual_entry',?,NOW())");
   $stmt->execute([$officeId,$visitDate,$sex,$age,$clientType,$service,$ratings[0],$ratings[1],$ratings[2],$ratings[3],$comment,$prediction['label'],$prediction['confidence'],$prediction['source'],$scores['average_rating'],$scores['rating_percent'],$scores['comment_score'],$scores['final_score'],(int)$user['id']]);$id=(int)db()->lastInsertId();create_action_if_needed($id,$officeId,$prediction['label'],$scores['final_score'],$comment);audit((int)$user['id'],'manual_feedback_entry',"Feedback #{$id}");set_flash('success','Historical feedback record added.');
  }elseif($action==='csv'){
   if(!isset($_FILES['csv_file'])||$_FILES['csv_file']['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Choose a valid CSV file.');
   $file=$_FILES['csv_file'];if((int)$file['size']>5*1024*1024)throw new RuntimeException('CSV file must not exceed 5 MB.');if(strtolower(pathinfo((string)$file['name'],PATHINFO_EXTENSION))!=='csv')throw new RuntimeException('Only .csv files are accepted.');
   $handle=fopen((string)$file['tmp_name'],'rb');if(!$handle)throw new RuntimeException('Unable to read the uploaded file.');$headers=fgetcsv($handle);if(!$headers)throw new RuntimeException('The CSV file has no header row.');$map=[];foreach($headers as $i=>$h)$map[normalize_header((string)$h)]=$i;
   $required=[['visit_date','date'],['sex'],['age'],['client_type','client_classification'],['service_received','service','transaction'],['timeliness','timeliness_rating'],['client_handling','client_handling_rating'],['quality_of_service','quality','quality_rating'],['overall_satisfaction','overall','overall_rating'],['comment','comments','suggestion']];
   foreach($required as $aliases){$found=false;foreach($aliases as $a)if(isset($map[$a]))$found=true;if(!$found)throw new RuntimeException('Missing required CSV column: '.$aliases[0]);}
   $valid=[];$errors=[];$rowNumber=1;
   while(($row=fgetcsv($handle))!==false){$rowNumber++;if(count(array_filter($row,fn($v)=>trim((string)$v)!==''))===0)continue;
    $record=['visit_date'=>csv_value($row,$map,['visit_date','date']),'sex'=>csv_value($row,$map,['sex']),'age'=>(int)csv_value($row,$map,['age']),'client_type'=>csv_value($row,$map,['client_type','client_classification']),'service'=>csv_value($row,$map,['service_received','service','transaction']),'ratings'=>[(int)csv_value($row,$map,['timeliness','timeliness_rating']),(int)csv_value($row,$map,['client_handling','client_handling_rating']),(int)csv_value($row,$map,['quality_of_service','quality','quality_rating']),(int)csv_value($row,$map,['overall_satisfaction','overall','overall_rating'])],'comment'=>csv_value($row,$map,['comment','comments','suggestion'])];
    $rowErrors=[];if(strtotime($record['visit_date'])===false||$record['visit_date']>date('Y-m-d'))$rowErrors[]='invalid or future date';if(!in_array($record['sex'],['Female','Male','Prefer not to say'],true))$rowErrors[]='invalid sex';if($record['age']<1||$record['age']>120)$rowErrors[]='invalid age';if(!in_array($record['client_type'],['Pasigueño','Non-Pasigueño','City Government Employee'],true))$rowErrors[]='invalid client type';if($record['service']==='')$rowErrors[]='missing service';if(array_filter($record['ratings'],fn($r)=>!valid_rating($r)))$rowErrors[]='ratings must be 1-4';if(mb_strlen($record['comment'])<5)$rowErrors[]='required comment is too short';
    if($rowErrors){$errors[]='Row '.$rowNumber.': '.implode(', ',$rowErrors);}else{$valid[]=$record;}
    if($rowNumber>10001){$errors[]='Import stopped after 10,000 data rows.';break;}
   }fclose($handle);
   $predictions=predict_sentiments_batch(array_column($valid,'comment'));$imported=0;db()->beginTransaction();
   $insert=db()->prepare("INSERT INTO feedback(office_id,visit_date,sex,age,client_type,service_received,timeliness_rating,client_handling_rating,quality_rating,overall_rating,comment,sentiment,sentiment_confidence,sentiment_source,average_rating,rating_percent,comment_score,final_score,source,imported_by_user_id,submitted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'csv_import',?,NOW())");
   foreach($valid as $i=>$record){$prediction=$predictions[$i]??predict_sentiment($record['comment']);$scores=compute_feedback_scores($record['ratings'],$prediction['label']);$insert->execute([$officeId,$record['visit_date'],$record['sex'],$record['age'],$record['client_type'],$record['service'],$record['ratings'][0],$record['ratings'][1],$record['ratings'][2],$record['ratings'][3],$record['comment'],$prediction['label'],$prediction['confidence'],$prediction['source'],$scores['average_rating'],$scores['rating_percent'],$scores['comment_score'],$scores['final_score'],(int)$user['id']]);$id=(int)db()->lastInsertId();create_action_if_needed($id,$officeId,$prediction['label'],$scores['final_score'],$record['comment']);$imported++;}
   $batch=db()->prepare('INSERT INTO import_batches(office_id,uploaded_by_user_id,original_filename,total_rows,imported_rows,rejected_rows,error_summary) VALUES(?,?,?,?,?,?,?)');$batch->execute([$officeId,(int)$user['id'],basename((string)$file['name']),count($valid)+count($errors),$imported,count($errors),implode("\n",array_slice($errors,0,100))]);db()->commit();audit((int)$user['id'],'csv_import',"Imported {$imported}, rejected ".count($errors));set_flash(count($errors)?'info':'success',"CSV import completed: {$imported} imported, ".count($errors).' rejected. Open Import History for details.');
  }
 }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();set_flash('error',$e->getMessage());}
 redirect('office/data.php');
}
$importsStmt=db()->prepare('SELECT * FROM import_batches WHERE office_id=? ORDER BY created_at DESC LIMIT 20');$importsStmt->execute([$officeId]);$imports=$importsStmt->fetchAll();
render_dashboard_start('Dataset & CSV Upload','data');page_header('Dataset & Historical Data','Office Heads can import only into their assigned office. Comments are required and classified by SVM.','<a class="btn secondary" href="'.e(app_url('sample_feedback_import.csv')).'" download>Download CSV Template</a>');
?>
<section class="card" style="margin-bottom:16px"><div class="card-head"><div><h2>How to Upload a CSV File</h2><p>Follow the visual guide and exact headers below.</p></div></div><img src="<?= e(app_url('assets/images/csv-guide.svg')) ?>" alt="CSV preparation, upload validation, and dashboard processing guide" style="width:100%;border-radius:15px"><div class="upload-guide"><div class="guide-step"><span class="num">1</span><strong>Download the template</strong><p>Keep the first row unchanged. Enter one client feedback response per succeeding row.</p></div><div class="guide-step"><span class="num">2</span><strong>Check allowed values</strong><p>Ratings: 1–4. Sex and client type must match the provided spelling. Every row needs a full comment.</p></div><div class="guide-step"><span class="num">3</span><strong>Upload and review</strong><p>The system validates rows, runs SVM predictions, computes 60/40 scores, and creates action items when needed.</p></div></div><div class="csv-preview">visit_date,sex,age,client_type,service_received,timeliness,client_handling,quality_of_service,overall_satisfaction,comment</div></section>
<div class="split-grid"><section class="panel-form"><h2>Upload Historical CSV</h2><p>Maximum 5 MB and 10,000 data rows. Invalid rows are rejected without changing valid rows.</p><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="csv"><div class="dropzone"><?= icon('upload') ?><strong style="display:block;margin-top:8px">Choose a CSV file</strong><input type="file" name="csv_file" accept=".csv,text/csv" required></div><button class="btn" style="margin-top:14px">Validate & Import CSV</button></form><div class="formula-box" style="margin-top:16px"><strong>Important</strong><br>Do not upload names, phone numbers, medical diagnoses, or other unnecessary identifiers. Historical comments should be de-identified before import.</div></section>
<section class="panel-form"><h2>Manual Historical Entry</h2><p>Use this for a small number of old paper feedback records.</p><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="manual"><div class="form-row three"><div class="form-group"><label>Date</label><input type="date" name="visit_date" required></div><div class="form-group"><label>Sex</label><select name="sex" required><option>Female</option><option>Male</option><option>Prefer not to say</option></select></div><div class="form-group"><label>Age</label><input type="number" name="age" min="1" max="120" required></div></div><div class="form-row"><div class="form-group"><label>Client Type</label><select name="client_type"><option>Pasigueño</option><option>Non-Pasigueño</option><option>City Government Employee</option></select></div><div class="form-group"><label>Service</label><input name="service_received" required></div></div><div class="form-row"><div class="form-group"><label>Timeliness (1-4)</label><input type="number" name="timeliness" min="1" max="4" required></div><div class="form-group"><label>Client Handling (1-4)</label><input type="number" name="client_handling" min="1" max="4" required></div></div><div class="form-row"><div class="form-group"><label>Quality (1-4)</label><input type="number" name="quality" min="1" max="4" required></div><div class="form-group"><label>Overall (1-4)</label><input type="number" name="overall" min="1" max="4" required></div></div><div class="form-group"><label>Required Comment</label><textarea name="comment" minlength="5" required></textarea></div><button class="btn">Add Record</button></form></section></div>
<section class="card" style="margin-top:16px"><div class="card-head"><div><h2>Import History</h2><p>Latest CSV processing results for <?= e($user['office_code']) ?></p></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Filename</th><th>Total</th><th>Imported</th><th>Rejected</th><th>Error Summary</th></tr></thead><tbody><?php foreach($imports as $i):?><tr><td><?= e(date('M d, Y h:i A',strtotime($i['created_at']))) ?></td><td><?= e($i['original_filename']) ?></td><td><?= (int)$i['total_rows'] ?></td><td><?= (int)$i['imported_rows'] ?></td><td><?= (int)$i['rejected_rows'] ?></td><td><pre style="white-space:pre-wrap;margin:0;max-width:420px"><?= e($i['error_summary']?:'No rejected rows.') ?></pre></td></tr><?php endforeach;?><?php if(!$imports):?><tr><td colspan="6" class="empty-state">No CSV imports yet.</td></tr><?php endif;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
