<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['office_head']);$officeId=(int)$user['office_id'];

function csv_value(array $row,array $map,array $aliases): string { foreach($aliases as $a)if(isset($map[$a]))return trim((string)($row[$map[$a]]??''));return ''; }
function preview_path(string $token): string { return __DIR__.'/../storage/import_previews/preview_'.$token.'.json'; }
function load_preview(string $token,array $user): ?array { if(!preg_match('/^[a-f0-9]{32}$/',$token))return null;$path=preview_path($token);if(!is_file($path))return null;$data=json_decode((string)file_get_contents($path),true);if(!is_array($data)||(int)($data['office_id']??0)!==(int)$user['office_id']||(int)($data['user_id']??0)!==(int)$user['id']||(int)($data['created_at']??0)<time()-3600)return null;return $data; }

if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=(string)($_POST['action']??'');
 try{
  if($action==='manual'){
   backfill_office_feedback_fingerprints($officeId);
   $visitDate=(string)($_POST['visit_date']??'');$sex=(string)($_POST['sex']??'');$age=(int)($_POST['age']??0);$client=(string)($_POST['client_type']??'');$service=trim((string)($_POST['service_received']??''));$comment=trim((string)($_POST['comment']??''));$ratings=[(int)($_POST['timeliness']??0),(int)($_POST['client_handling']??0),(int)($_POST['quality']??0),(int)($_POST['overall']??0)];
   if(strtotime($visitDate)===false||$visitDate>date('Y-m-d')||!in_array($sex,['Female','Male','Prefer not to say'],true)||$age<1||$age>120||!in_array($client,['Pasigueño','Non-Pasigueño','City Government Employee'],true)||$service===''||array_filter($ratings,fn($r)=>!valid_rating($r))||mb_strlen($comment)<5)throw new RuntimeException('Complete all manual-entry fields using valid values.');
   $record=['visit_date'=>$visitDate,'sex'=>$sex,'age'=>$age,'client_type'=>$client,'service'=>$service,'ratings'=>$ratings,'comment'=>$comment];$fingerprint=feedback_fingerprint($officeId,$record);$dup=db()->prepare('SELECT id FROM feedback WHERE office_id=? AND record_fingerprint=? AND is_void=0 LIMIT 1');$dup->execute([$officeId,$fingerprint]);if($dup->fetchColumn())throw new RuntimeException('This exact historical record already exists.');
   $prediction=predict_sentiment($comment);$scores=compute_feedback_scores($ratings,$prediction['label']);$reviewStatus=prediction_review_status($prediction);$stmt=db()->prepare("INSERT INTO feedback(office_id,visit_date,sex,age,client_type,service_received,timeliness_rating,client_handling_rating,quality_rating,overall_rating,comment,sentiment,original_sentiment,sentiment_confidence,sentiment_source,review_status,model_version,average_rating,rating_percent,comment_score,final_score,source,record_fingerprint,imported_by_user_id,submitted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'manual_entry',?,?,NOW())");$stmt->execute([$officeId,$visitDate,$sex,$age,$client,$service,$ratings[0],$ratings[1],$ratings[2],$ratings[3],$comment,$prediction['label'],$prediction['label'],$prediction['confidence'],$prediction['source'],$reviewStatus,model_version(),$scores['average_rating'],$scores['rating_percent'],$scores['comment_score'],$scores['final_score'],$fingerprint,(int)$user['id']]);$id=(int)db()->lastInsertId();create_action_if_needed($id,$officeId,$prediction['label'],$scores['final_score'],$comment);audit((int)$user['id'],'manual_feedback_create',"Feedback #{$id}, review={$reviewStatus}");set_flash('success','Historical feedback added and processed.');
  }elseif($action==='preview'){
   backfill_office_feedback_fingerprints($officeId);
   if(!isset($_FILES['csv_file'])||$_FILES['csv_file']['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Choose a valid CSV file.');$file=$_FILES['csv_file'];if((int)$file['size']>5*1024*1024)throw new RuntimeException('CSV file must not exceed 5 MB.');if(strtolower(pathinfo((string)$file['name'],PATHINFO_EXTENSION))!=='csv')throw new RuntimeException('Only .csv files are accepted.');
   $mime=class_exists('finfo')?(new finfo(FILEINFO_MIME_TYPE))->file((string)$file['tmp_name']):(mime_content_type((string)$file['tmp_name'])?:'text/plain');if(!in_array($mime,['text/plain','text/csv','application/csv','application/vnd.ms-excel','application/octet-stream'],true))throw new RuntimeException('The uploaded file does not appear to be a valid CSV file.');
   $handle=fopen((string)$file['tmp_name'],'rb');if(!$handle)throw new RuntimeException('Unable to read the uploaded file.');$headers=fgetcsv($handle);if(!$headers)throw new RuntimeException('The CSV file has no header row.');$headers[0]=preg_replace('/^\xEF\xBB\xBF/','',(string)$headers[0]);$map=[];foreach($headers as $i=>$h)$map[normalize_header((string)$h)]=$i;
   $required=[['visit_date','date'],['sex'],['age'],['client_type','client_classification'],['service_received','service','transaction'],['timeliness','timeliness_rating'],['client_handling','client_handling_rating'],['quality_of_service','quality','quality_rating'],['overall_satisfaction','overall','overall_rating'],['comment','comments','suggestion']];foreach($required as $aliases){$found=false;foreach($aliases as $a)if(isset($map[$a]))$found=true;if(!$found)throw new RuntimeException('Missing required CSV column: '.$aliases[0]);}
   $existing=[];$ex=db()->prepare('SELECT record_fingerprint FROM feedback WHERE office_id=? AND record_fingerprint IS NOT NULL AND is_void=0');$ex->execute([$officeId]);foreach($ex->fetchAll(PDO::FETCH_COLUMN) as $fp)$existing[(string)$fp]=true;$seen=[];$valid=[];$rejected=[];$duplicates=0;$rowNumber=1;
   while(($row=fgetcsv($handle))!==false){$rowNumber++;if(count(array_filter($row,fn($v)=>trim((string)$v)!==''))===0)continue;$record=['visit_date'=>csv_value($row,$map,['visit_date','date']),'sex'=>csv_value($row,$map,['sex']),'age'=>(int)csv_value($row,$map,['age']),'client_type'=>csv_value($row,$map,['client_type','client_classification']),'service'=>csv_value($row,$map,['service_received','service','transaction']),'ratings'=>[(int)csv_value($row,$map,['timeliness','timeliness_rating']),(int)csv_value($row,$map,['client_handling','client_handling_rating']),(int)csv_value($row,$map,['quality_of_service','quality','quality_rating']),(int)csv_value($row,$map,['overall_satisfaction','overall','overall_rating'])],'comment'=>csv_value($row,$map,['comment','comments','suggestion'])];$errs=[];if(strtotime($record['visit_date'])===false||$record['visit_date']>date('Y-m-d'))$errs[]='invalid or future date';if(!in_array($record['sex'],['Female','Male','Prefer not to say'],true))$errs[]='invalid sex';if($record['age']<1||$record['age']>120)$errs[]='invalid age';if(!in_array($record['client_type'],['Pasigueño','Non-Pasigueño','City Government Employee'],true))$errs[]='invalid client type';if($record['service']==='')$errs[]='missing service';if(array_filter($record['ratings'],fn($r)=>!valid_rating($r)))$errs[]='ratings must be 1-4';if(mb_strlen($record['comment'])<5)$errs[]='required comment is too short';$fp=feedback_fingerprint($officeId,$record);$record['fingerprint']=$fp;if(isset($existing[$fp])||isset($seen[$fp])){$errs[]='duplicate record';$duplicates++;}$seen[$fp]=true;if($errs)$rejected[]=['row_number'=>$rowNumber,'raw_row'=>$row,'error'=>implode(', ',$errs)];else$valid[]=$record;if($rowNumber>10001){$rejected[]=['row_number'=>$rowNumber,'raw_row'=>[],'error'=>'Import stopped after 10,000 data rows.'];break;}}
   fclose($handle);$token=bin2hex(random_bytes(16));$dir=dirname(preview_path($token));if(!is_dir($dir))mkdir($dir,0775,true);$preview=['token'=>$token,'office_id'=>$officeId,'user_id'=>(int)$user['id'],'created_at'=>time(),'filename'=>basename((string)$file['name']),'mime'=>$mime,'valid'=>$valid,'rejected'=>$rejected,'duplicates'=>$duplicates];file_put_contents(preview_path($token),json_encode($preview,JSON_UNESCAPED_UNICODE));audit((int)$user['id'],'csv_preview',"{$preview['filename']}: valid=".count($valid).', rejected='.count($rejected).", duplicates={$duplicates}");redirect('office/data.php?preview='.$token);
  }elseif($action==='confirm'){
   $token=(string)($_POST['preview_token']??'');$preview=load_preview($token,$user);if(!$preview)throw new RuntimeException('The import preview expired or is invalid. Upload the CSV again.');$valid=$preview['valid'];$rejected=$preview['rejected'];$predictions=predict_sentiments_batch(array_column($valid,'comment'));db()->beginTransaction();$batch=db()->prepare('INSERT INTO import_batches(office_id,uploaded_by_user_id,original_filename,total_rows,imported_rows,rejected_rows,duplicate_rows,preview_token,error_summary) VALUES(?,?,?,?,0,?,?,?,?)');$batch->execute([$officeId,(int)$user['id'],$preview['filename'],count($valid)+count($rejected),count($rejected),(int)$preview['duplicates'],$token,implode("\n",array_map(fn($r)=>'Row '.$r['row_number'].': '.$r['error'],array_slice($rejected,0,100)))]);$batchId=(int)db()->lastInsertId();
   $actionCount=0;$insert=db()->prepare("INSERT INTO feedback(office_id,visit_date,sex,age,client_type,service_received,timeliness_rating,client_handling_rating,quality_rating,overall_rating,comment,sentiment,original_sentiment,sentiment_confidence,sentiment_source,review_status,model_version,average_rating,rating_percent,comment_score,final_score,source,record_fingerprint,import_batch_id,imported_by_user_id,submitted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'csv_import',?,?,?,NOW())");$imported=0;$reviewCount=0;
   foreach($valid as $i=>$record){$prediction=$predictions[$i]??predict_sentiment($record['comment']);$scores=compute_feedback_scores($record['ratings'],$prediction['label']);$reviewStatus=prediction_review_status($prediction);if($reviewStatus==='needs_review')$reviewCount++;$insert->execute([$officeId,$record['visit_date'],$record['sex'],$record['age'],$record['client_type'],$record['service'],$record['ratings'][0],$record['ratings'][1],$record['ratings'][2],$record['ratings'][3],$record['comment'],$prediction['label'],$prediction['label'],$prediction['confidence'],$prediction['source'],$reviewStatus,model_version(),$scores['average_rating'],$scores['rating_percent'],$scores['comment_score'],$scores['final_score'],$record['fingerprint'],$batchId,(int)$user['id']]);$id=(int)db()->lastInsertId();if(create_action_if_needed($id,$officeId,$prediction['label'],$scores['final_score'],$record['comment'],false)!==null)$actionCount++;$imported++;}
   $rejStmt=db()->prepare('INSERT INTO import_rejected_rows(import_batch_id,row_number,raw_row,error_message) VALUES(?,?,?,?)');foreach($rejected as $r)$rejStmt->execute([$batchId,(int)$r['row_number'],json_encode($r['raw_row'],JSON_UNESCAPED_UNICODE),(string)$r['error']]);db()->prepare('UPDATE import_batches SET imported_rows=? WHERE id=?')->execute([$imported,$batchId]);db()->commit();@unlink(preview_path($token));if($actionCount){notify_office_heads($officeId,'action','Imported feedback created actions',"{$actionCount} action item(s) were created from import #{$batchId}.",'office/actions.php');notify_admins('action','Import created action items',$user['office_code']." import #{$batchId} created {$actionCount} action item(s).",'admin/actions.php');}if($reviewCount){notify_office_heads($officeId,'review','Imported feedback requires review',"{$reviewCount} record(s) from import #{$batchId} require sentiment review.",'review.php');notify_admins('review','Imported feedback requires review',$user['office_code']." import #{$batchId} has {$reviewCount} review item(s).",'review.php');}audit((int)$user['id'],'csv_import',"Batch #{$batchId}: imported={$imported}, rejected=".count($rejected).', duplicates='.(int)$preview['duplicates']);set_flash(count($rejected)?'info':'success',"CSV import completed: {$imported} imported, ".count($rejected).' rejected.');
  }elseif($action==='rollback'){
   $batchId=post_int('batch_id');$stmt=db()->prepare('SELECT * FROM import_batches WHERE id=? AND office_id=? AND rolled_back_at IS NULL');$stmt->execute([$batchId,$officeId]);$batch=$stmt->fetch();if(!$batch)throw new RuntimeException('Import batch not found or already rolled back.');db()->beginTransaction();db()->prepare('DELETE a FROM actions a JOIN feedback f ON f.id=a.feedback_id WHERE f.import_batch_id=? AND f.office_id=?')->execute([$batchId,$officeId]);db()->prepare('DELETE FROM feedback WHERE import_batch_id=? AND office_id=?')->execute([$batchId,$officeId]);db()->prepare('UPDATE import_batches SET rolled_back_at=NOW(),rolled_back_by_user_id=? WHERE id=?')->execute([(int)$user['id'],$batchId]);db()->commit();audit((int)$user['id'],'csv_import_rollback',"Rolled back import batch #{$batchId}");set_flash('success','Imported feedback and generated actions were rolled back. Import history was retained.');
  }
 }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();set_flash('error',$e->getMessage());}
 redirect('office/data.php');
}
$previewToken=(string)($_GET['preview']??'');$preview=$previewToken!==''?load_preview($previewToken,$user):null;$importsStmt=db()->prepare('SELECT * FROM import_batches WHERE office_id=? ORDER BY created_at DESC LIMIT 30');$importsStmt->execute([$officeId]);$imports=$importsStmt->fetchAll();
render_dashboard_start('Dataset & CSV Upload','data');page_header('Dataset & Historical Data','CSV files are previewed before import, checked for duplicates, classified in batch, and remain rollback-capable.','<a class="btn secondary" href="'.e(app_url('sample_feedback_import.csv')).'" download>Download CSV Template</a>');
?>
<?php if($preview): ?><section class="card preview-card"><div class="card-head"><div><h2>Import Preview: <?= e($preview['filename']) ?></h2><p>Nothing has been saved yet. Confirm only after reviewing the validation results.</p></div></div><div class="stats-grid"><div class="stat-card highlight"><small>Valid Rows</small><strong><?= count($preview['valid']) ?></strong></div><div class="stat-card"><small>Rejected Rows</small><strong><?= count($preview['rejected']) ?></strong></div><div class="stat-card"><small>Duplicates</small><strong><?= (int)$preview['duplicates'] ?></strong></div><div class="stat-card"><small>MIME</small><strong class="small-stat"><?= e($preview['mime']) ?></strong></div></div><div class="content-grid"><div><h3>First Valid Rows</h3><div class="table-wrap"><table><thead><tr><th>Date</th><th>Service</th><th>Ratings</th><th>Comment</th></tr></thead><tbody><?php foreach(array_slice($preview['valid'],0,10) as $r):?><tr><td><?= e($r['visit_date']) ?></td><td><?= e($r['service']) ?></td><td><?= e(implode('/',$r['ratings'])) ?></td><td><?= e($r['comment']) ?></td></tr><?php endforeach;?></tbody></table></div></div><div><h3>Rejected Examples</h3><div class="table-wrap"><table><thead><tr><th>Row</th><th>Error</th></tr></thead><tbody><?php foreach(array_slice($preview['rejected'],0,10) as $r):?><tr><td><?= (int)$r['row_number'] ?></td><td><?= e($r['error']) ?></td></tr><?php endforeach;?><?php if(!$preview['rejected']):?><tr><td colspan="2">No rejected rows.</td></tr><?php endif;?></tbody></table></div></div></div><form method="post" class="actions-cell"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="confirm"><input type="hidden" name="preview_token" value="<?= e($previewToken) ?>"><button class="btn success">Confirm Import</button><a class="btn secondary" href="<?= e(app_url('office/data.php')) ?>">Cancel Preview</a></form></section><?php endif; ?>
<section class="card" style="margin-bottom:16px"><div class="card-head"><div><h2>How to Upload a CSV File</h2><p>Download → validate/preview → confirm → review rejected rows or rollback the batch.</p></div></div><img src="<?= e(app_url('assets/images/csv-guide.svg')) ?>" alt="CSV preparation, upload validation, and dashboard processing guide" style="width:100%;border-radius:15px"><div class="upload-guide"><div class="guide-step"><span class="num">1</span><strong>Prepare the template</strong><p>Keep the headers unchanged. Remove names, contact information, diagnoses, and identifiers.</p></div><div class="guide-step"><span class="num">2</span><strong>Preview validation</strong><p>The system checks MIME type, required columns, dates, allowed values, ratings, comments, and duplicates before saving.</p></div><div class="guide-step"><span class="num">3</span><strong>Confirm or cancel</strong><p>Valid rows are imported only after confirmation. Rejected rows are downloadable and the whole batch can be rolled back.</p></div></div><div class="csv-preview">visit_date,sex,age,client_type,service_received,timeliness,client_handling,quality_of_service,overall_satisfaction,comment</div></section>
<div class="split-grid"><section class="panel-form"><h2>Upload Historical CSV</h2><p>Maximum 5 MB and 10,000 data rows.</p><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="preview"><div class="dropzone"><?= icon('upload') ?><strong style="display:block;margin-top:8px">Choose a CSV file</strong><input type="file" name="csv_file" accept=".csv,text/csv" required></div><button class="btn" style="margin-top:14px">Validate & Preview CSV</button></form></section>
<section class="panel-form"><h2>Manual Historical Entry</h2><p>Exact duplicates are blocked.</p><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="manual"><div class="form-row three"><div class="form-group"><label>Date</label><input type="date" name="visit_date" max="<?= e(date('Y-m-d')) ?>" required></div><div class="form-group"><label>Sex</label><select name="sex" required><option>Female</option><option>Male</option><option>Prefer not to say</option></select></div><div class="form-group"><label>Age</label><input type="number" name="age" min="1" max="120" required></div></div><div class="form-row"><div class="form-group"><label>Client Type</label><select name="client_type"><option>Pasigueño</option><option>Non-Pasigueño</option><option>City Government Employee</option></select></div><div class="form-group"><label>Service</label><input name="service_received" required></div></div><div class="form-row"><div class="form-group"><label>Timeliness (1-4)</label><input type="number" name="timeliness" min="1" max="4" required></div><div class="form-group"><label>Client Handling (1-4)</label><input type="number" name="client_handling" min="1" max="4" required></div></div><div class="form-row"><div class="form-group"><label>Quality (1-4)</label><input type="number" name="quality" min="1" max="4" required></div><div class="form-group"><label>Overall (1-4)</label><input type="number" name="overall" min="1" max="4" required></div></div><div class="form-group"><label>Required Comment</label><textarea name="comment" minlength="5" required></textarea></div><button class="btn">Add Record</button></form></section></div>
<section class="card" style="margin-top:16px"><div class="card-head"><div><h2>Import History</h2><p>Rejected-row downloads and one-click rollback are available.</p></div></div><div class="table-wrap"><table><thead><tr><th>Date / File</th><th>Total</th><th>Imported</th><th>Rejected</th><th>Duplicates</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($imports as $i):?><tr><td><?= e(date('M d, Y h:i A',strtotime($i['created_at']))) ?><br><span class="muted"><?= e($i['original_filename']) ?></span></td><td><?= (int)$i['total_rows'] ?></td><td><?= (int)$i['imported_rows'] ?></td><td><?= (int)$i['rejected_rows'] ?></td><td><?= (int)$i['duplicate_rows'] ?></td><td><?= $i['rolled_back_at']?badge('Rolled Back','negative'):badge('Active','positive') ?></td><td class="actions-cell"><?php if((int)$i['rejected_rows']>0):?><a class="btn secondary small" href="<?= e(app_url('office/rejected_rows.php?batch_id='.(int)$i['id'])) ?>">Download Rejected CSV</a><?php endif;?><?php if(!$i['rolled_back_at']&&(int)$i['imported_rows']>0):?><form method="post" data-confirm-delete="Rollback all feedback and generated actions from this import batch?"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="rollback"><input type="hidden" name="batch_id" value="<?= (int)$i['id'] ?>"><button class="btn danger small">Rollback Batch</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$imports):?><tr><td colspan="7" class="empty-state">No CSV imports yet.</td></tr><?php endif;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
