<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['office_head','office_staff']);$officeId=(int)$user['office_id'];$sentiment=trim((string)($_GET['sentiment']??''));$review=trim((string)($_GET['review']??''));$dateFrom=trim((string)($_GET['date_from']??''));$dateTo=trim((string)($_GET['date_to']??''));$q=trim((string)($_GET['q']??''));$includeVoid=isset($_GET['include_void'])&&$user['role']==='office_head';
$where=['f.office_id=?'];$params=[$officeId];
if(in_array($sentiment,['positive','neutral','negative'],true)){$where[]='f.sentiment=?';$params[]=$sentiment;}
if(in_array($review,['not_required','needs_review','reviewed'],true)){$where[]='f.review_status=?';$params[]=$review;}
if($dateFrom!==''){$where[]='f.visit_date>=?';$params[]=$dateFrom;}if($dateTo!==''){$where[]='f.visit_date<=?';$params[]=$dateTo;}if(!$includeVoid)$where[]='f.is_void=0';if($q!==''){$where[]='(f.comment LIKE ? OR f.service_received LIKE ? OR CAST(f.id AS CHAR)=?)';$params[]="%{$q}%";$params[]="%{$q}%";$params[]=$q;}
$count=db()->prepare('SELECT COUNT(*) FROM feedback f WHERE '.implode(' AND ',$where));$count->execute($params);$p=pagination((int)$count->fetchColumn(),25);$stmt=db()->prepare("SELECT f.* FROM feedback f WHERE ".implode(' AND ',$where)." ORDER BY f.submitted_at DESC LIMIT {$p['per_page']} OFFSET {$p['offset']}");$stmt->execute($params);$rows=$stmt->fetchAll();
render_dashboard_start('Feedback Records','feedback');page_header($user['office_code'].' Feedback Records','Every result is restricted to '.$user['office_name'].'.',$user['role']==='office_head'?'<a class="btn" href="'.e(app_url('review.php')).'">Review Sentiments</a>':'');
?>
<form class="filters wide" method="get"><select name="sentiment"><option value="">All sentiments</option><?php foreach(['positive','neutral','negative'] as $v):?><option value="<?= $v ?>" <?= $sentiment===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><select name="review"><option value="">All review states</option><?php foreach(['needs_review','reviewed','not_required'] as $v):?><option value="<?= $v ?>" <?= $review===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><label class="filter-field"><span>From</span><input type="date" name="date_from" value="<?= e($dateFrom) ?>"></label><label class="filter-field"><span>To</span><input type="date" name="date_to" value="<?= e($dateTo) ?>"></label><input name="q" value="<?= e($q) ?>" placeholder="Search ID, service, comment"><?php if($user['role']==='office_head'): ?><label class="checkbox-inline"><input type="checkbox" name="include_void" value="1" <?= $includeVoid?'checked':'' ?>> Include void</label><?php endif; ?><button class="btn">Apply</button></form>
<section class="card"><div class="table-wrap"><table><thead><tr><th>ID / Date</th><th>Service</th><th>Client</th><th>Rating</th><th>Sentiment</th><th>Final</th><th>Comment</th></tr></thead><tbody><?php foreach($rows as $r):?><tr class="<?= $r['is_void']?'void-row':'' ?>"><td><strong>#<?= (int)$r['id'] ?></strong><br><?= e($r['visit_date']) ?><?php if($r['is_void']): ?><br><?= badge('Void','negative') ?><?php endif; ?></td><td><?= e($r['service_received']) ?><br><span class="muted"><?= e(status_label($r['source'])) ?></span></td><td><?= e($r['sex']) ?>, <?= (int)$r['age'] ?><br><span class="muted"><?= e($r['client_type']) ?></span></td><td><?= number_format((float)$r['average_rating'],2) ?>/4</td><td><?= badge(status_label($r['sentiment']),$r['sentiment']) ?><br><span class="muted"><?= number_format((float)$r['sentiment_confidence']*100,2) ?>% · <?= e($r['sentiment_source']) ?></span><br><?= badge(status_label($r['review_status']),$r['review_status']==='needs_review'?'negative':'positive') ?></td><td><?= number_format((float)$r['final_score'],2) ?>%</td><td><?= e($r['comment']) ?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="7" class="empty-state">No feedback records match the filters.</td></tr><?php endif;?></tbody></table></div><?= pagination_links($p) ?></section>
<?php render_dashboard_end(); ?>
