<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['office_head','office_staff']);$officeId=(int)$user['office_id'];$sentiment=trim((string)($_GET['sentiment']??''));$source=trim((string)($_GET['source']??''));$dateFrom=trim((string)($_GET['date_from']??''));$dateTo=trim((string)($_GET['date_to']??''));$where=['f.office_id=?'];$params=[$officeId];if(in_array($sentiment,['positive','neutral','negative'],true)){$where[]='f.sentiment=?';$params[]=$sentiment;}if(in_array($source,['public_survey','csv_import','manual_entry'],true)){$where[]='f.source=?';$params[]=$source;}if($dateFrom!==''){$where[]='f.visit_date>=?';$params[]=$dateFrom;}if($dateTo!==''){$where[]='f.visit_date<=?';$params[]=$dateTo;}$stmt=db()->prepare("SELECT f.* FROM feedback f WHERE ".implode(' AND ',$where)." ORDER BY f.submitted_at DESC LIMIT 500");$stmt->execute($params);$rows=$stmt->fetchAll();
render_dashboard_start('Office Feedback','feedback');page_header($user['office_code'].' Feedback Records','Only records assigned to '.$user['office_name'].' are returned.');
?>
<form class="filters" method="get"><select name="sentiment"><option value="">All sentiments</option><?php foreach(['positive','neutral','negative'] as $v):?><option value="<?= $v ?>" <?= $sentiment===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><select name="source"><option value="">All sources</option><?php foreach(['public_survey','csv_import','manual_entry'] as $v):?><option value="<?= $v ?>" <?= $source===$v?'selected':'' ?>><?= e(status_label($v)) ?></option><?php endforeach;?></select><input type="date" name="date_from" value="<?= e($dateFrom) ?>"><input type="date" name="date_to" value="<?= e($dateTo) ?>"><button class="btn">Filter</button></form>
<section class="card"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Client</th><th>Service</th><th>Ratings</th><th>SVM Sentiment</th><th>Final</th><th>Comment</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?= e(date('M d, Y',strtotime($r['visit_date']))) ?><br><span class="muted"><?= e(status_label($r['source'])) ?></span></td><td><?= e($r['sex']) ?>, <?= (int)$r['age'] ?><br><span class="muted"><?= e($r['client_type']) ?></span></td><td><?= e($r['service_received']) ?></td><td>T<?= (int)$r['timeliness_rating'] ?> H<?= (int)$r['client_handling_rating'] ?> Q<?= (int)$r['quality_rating'] ?> O<?= (int)$r['overall_rating'] ?><br><span class="muted"><?= number_format((float)$r['average_rating'],2) ?>/4</span></td><td><?= badge(status_label($r['sentiment']),$r['sentiment']) ?><br><span class="muted"><?= e(strtoupper($r['sentiment_source'])) ?> <?= number_format((float)$r['sentiment_confidence']*100,1) ?>%</span></td><td><strong><?= number_format((float)$r['final_score'],2) ?>%</strong><br><span class="muted"><?= e(final_interpretation((float)$r['final_score'])) ?></span></td><td><?= e($r['comment']) ?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="7" class="empty-state">No office feedback matches the filters.</td></tr><?php endif;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
