<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user=require_login(['office_head','office_staff']);$officeId=(int)$user['office_id'];$dateFrom=trim((string)($_GET['date_from']??''));$dateTo=trim((string)($_GET['date_to']??''));$includeVoid=isset($_GET['include_void'])&&$user['role']==='office_head';$where=['f.office_id=?'];$params=[$officeId];if($dateFrom!==''){$where[]='f.visit_date>=?';$params[]=$dateFrom;}if($dateTo!==''){$where[]='f.visit_date<=?';$params[]=$dateTo;}if(!$includeVoid)$where[]='f.is_void=0';$stmt=db()->prepare("SELECT f.* FROM feedback f WHERE ".implode(' AND ',$where)." ORDER BY f.visit_date DESC,f.id DESC");$stmt->execute($params);$rows=$stmt->fetchAll();
if(($_GET['export']??'')==='csv'){$export=[];foreach($rows as $r)$export[]=[$r['id'],$r['visit_date'],$r['sex'],$r['age'],$r['client_type'],$r['service_received'],$r['timeliness_rating'],$r['client_handling_rating'],$r['quality_rating'],$r['overall_rating'],$r['average_rating'],$r['comment'],$r['sentiment'],$r['sentiment_confidence'],$r['sentiment_source'],$r['review_status'],$r['final_score'],$r['source'],$r['submitted_at']];audit((int)$user['id'],'report_csv_export',$user['office_code'].' exported '.count($rows).' rows');csv_download(strtolower($user['office_code']).'-feedback-'.date('Y-m-d').'.csv',['ID','Visit Date','Sex','Age','Client Type','Service','Timeliness','Client Handling','Quality','Overall','Average Rating','Comment','Sentiment','Confidence','Classifier Source','Review Status','Final Score','Record Source','Submitted At'],$export);}
$m=dashboard_metrics($officeId,$dateFrom?:null,$dateTo?:null,true,$includeVoid);$ages=age_group_counts($officeId,$dateFrom?:null,$dateTo?:null,true,$includeVoid);$services=service_summary($officeId,10,$dateFrom?:null,$dateTo?:null,true,$includeVoid);render_dashboard_start('Office Reports','reports');page_header($user['office_code'].' Reports & Export','Every summary and detailed row follows the selected date range.','<button class="btn secondary" onclick="window.print()">Print / Save as PDF</button>');
?>
<form class="filters wide" method="get"><label class="filter-field"><span>From</span><input type="date" name="date_from" value="<?= e($dateFrom) ?>"></label><label class="filter-field"><span>To</span><input type="date" name="date_to" value="<?= e($dateTo) ?>"></label><?php if($user['role']==='office_head'): ?><label class="checkbox-inline"><input type="checkbox" name="include_void" value="1" <?= $includeVoid?'checked':'' ?>> Include void</label><?php endif; ?><button class="btn">Generate</button><button class="btn success" name="export" value="csv">Download CSV</button></form>
<div class="stats-grid"><div class="stat-card"><small>Responses</small><strong><?= count($rows) ?></strong></div><div class="stat-card"><small>Average Rating</small><strong><?= number_format($m['avg_rating'],2) ?>/4</strong></div><div class="stat-card"><small>Final Score</small><strong><?= number_format($m['avg_final'],2) ?>%</strong></div><div class="stat-card"><small>Positive Rate</small><strong><?= number_format($m['positive_rate'],1) ?>%</strong></div><div class="stat-card"><small>Action Completion</small><strong><?= number_format($m['completion_rate'],1) ?>%</strong></div></div>
<div class="content-grid"><section class="card"><div class="card-head"><div><h2>Age Groups</h2></div></div><div class="chart-box"><canvas data-chart='<?= e(json_encode(array_map(fn($r)=>['label'=>$r['label'],'value'=>(int)$r['count']],$ages))) ?>' data-type="bar"></canvas></div></section><section class="card"><div class="card-head"><div><h2>Service Performance</h2></div></div><div class="table-wrap"><table><thead><tr><th>Service</th><th>Responses</th><th>Score</th><th>Negative</th></tr></thead><tbody><?php foreach($services as $s):?><tr><td><?= e($s['label']) ?></td><td><?= (int)$s['responses'] ?></td><td><?= number_format((float)$s['avg_score'],2) ?>%</td><td><?= (int)$s['negative_count'] ?></td></tr><?php endforeach;?></tbody></table></div></section></div>
<section class="card"><div class="card-head"><div><h2><?= e($user['office_name']) ?> Feedback Report</h2><p><?= count($rows) ?> record(s)</p></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Service</th><th>Client</th><th>Rating</th><th>Sentiment</th><th>Final</th><th>Comment</th></tr></thead><tbody><?php foreach($rows as $r):?><tr class="<?= $r['is_void']?'void-row':'' ?>"><td><?= e($r['visit_date']) ?></td><td><?= e($r['service_received']) ?></td><td><?= e($r['client_type']) ?><br><span class="muted"><?= (int)$r['age'] ?> · <?= e($r['sex']) ?></span></td><td><?= number_format((float)$r['average_rating'],2) ?>/4</td><td><?= badge(status_label($r['sentiment']),$r['sentiment']) ?><br><span class="muted"><?= e($r['review_status']) ?></span></td><td><?= number_format((float)$r['final_score'],2) ?>%</td><td><?= e($r['comment']) ?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="7" class="empty-state">No records in this date range.</td></tr><?php endif;?></tbody></table></div></section>
<?php render_dashboard_end(); ?>
